# -*- coding: utf-8 -*-
"""Export the corpus and the analysis output as Excel workbooks.

Two workbooks are written to ../export/:

*   ``EMA_raw_data.xlsx`` — the corpus itself, at both levels at which it
    exists: one row per participant and one row per scheduled prompt.
    Latent variables that the models never see are included and marked
    as such, because they are what the evaluation is validated against.
*   ``EMA_analysis_results.xlsx`` — every table and diagnostic reported
    in the manuscript, read back from the JSON the protocol writes.

Both are regenerated from the same seed as the manuscript, so re-running
this script reproduces the files byte-for-byte in content.

Usage:  python3 export_data.py
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "model"))
TAB = os.path.join(ROOT, "tables")
OUT = os.path.join(ROOT, "export")
os.makedirs(OUT, exist_ok=True)

import ema_data as D                                    # noqa: E402

HEAD_FILL = PatternFill("solid", fgColor="DDDDDD")
HEAD_FONT = Font(bold=True)
WRAP = Alignment(wrap_text=True, vertical="top")


# ---------------------------------------------------------------------------
def sheet(wb, title, rows, widths=None, freeze="A2", wrap_cols=()):
    """Write a list-of-lists to a new worksheet with a styled header."""
    ws = wb.create_sheet(title=title)
    for r in rows:
        ws.append(list(r))
    for c in range(1, len(rows[0]) + 1):
        cell = ws.cell(row=1, column=c)
        cell.fill = HEAD_FILL
        cell.font = HEAD_FONT
        cell.alignment = Alignment(wrap_text=True, vertical="center")
    ws.freeze_panes = freeze
    if widths:
        for i, w in enumerate(widths, start=1):
            ws.column_dimensions[get_column_letter(i)].width = w
    for col in wrap_cols:
        for row in ws.iter_rows(min_row=2, min_col=col, max_col=col):
            for cell in row:
                cell.alignment = WRAP
    return ws


def note_sheet(wb, title, paragraphs, width=118):
    ws = wb.create_sheet(title=title)
    ws.column_dimensions["A"].width = width
    for i, p in enumerate(paragraphs, start=1):
        ws.cell(row=i, column=1, value=p).alignment = WRAP
        if p and not p.startswith(" ") and p.endswith("】"):
            ws.cell(row=i, column=1).font = Font(bold=True)
    return ws


def lag1(v):
    if len(v) < 3:
        return float("nan")
    return float(np.corrcoef(v[:-1], v[1:])[0, 1])


# ---------------------------------------------------------------------------
def raw_workbook(data, tr, va, te):
    n, T, F = data["X_raw"].shape
    X, mask, used = data["X_raw"], data["mask"], data["used"]
    q = data["quest"]
    split = np.empty(n, dtype=object)
    split[tr], split[va], split[te] = "train", "validation", "test"

    wb = Workbook()
    wb.remove(wb.active)

    note_sheet(wb, "说明 Readme", [
        "【本文件是什么 What this file is】",
        "本工作簿是论文《Dual-Pathway Affective Process Tracing for "
        "Auditable Assessment of Emotion Regulation in Daily Life》所用"
        "语料的完整原始数据。",
        "This workbook holds the complete corpus used in the paper.",
        "",
        "【重要：这是模拟数据，不是真实调查 IMPORTANT: simulated, not "
        "collected】",
        "这 420 名「参与者」由一个显式的、带随机种子的心理过程模型生成，"
        "不是真人填答。论文摘要与第五节均已声明这一点。",
        "选择模拟的原因：本文的核心指标 justification alignment 需要知道"
        "每个时刻实际部署了哪一族调节策略（下表 deployed_family 列）。"
        "任何观测语料都无法确定地提供这一标签，因此该指标只有在模拟条件"
        "下可算。这是方法上的取舍，论文第七节 C 小节把它同时列为本研究的"
        "局限。",
        "The 420 participants are generated by an explicit seeded "
        "psychological process model, not collected from people. The "
        "episode-level ground truth in the deployed_family column is "
        "what makes justification alignment computable, and no "
        "observational corpus supplies it with certainty.",
        "",
        "【生成参数 Generative parameters】",
        f"随机种子 seed = {D.SEED}；参与者 = {D.N_PART}；天数 = "
        f"{D.N_DAYS}；每天提示次数 = {D.N_PROMPT}；计划提示总数 = "
        f"{D.T_MAX}；应答率 compliance = {D.COMPLIANCE}",
        "结构参数锚定于已发表数值：情绪惯性（瞬时负性情绪的一阶自相关）"
        "中心 0.35；ERQ 重评 M = 4.9, SD = 0.9；ERQ 抑制 M = 3.4, "
        "SD = 1.1；DERS M = 80, SD = 20；信号取样设计的应答率 85%。",
        "",
        "【如何重新生成 How to regenerate】",
        "cd model && python3 -c \"import ema_data; ema_data.generate()\"",
        "cd analysis && python3 export_data.py   # 重新导出本工作簿",
        "生成代码：model/ema_data.py（同一种子下结果完全可复现）",
        "",
        "【工作表 Sheets】",
        "参与者层 Participants：420 行，每名参与者一行。",
        f"情节层 Episodes：{n * T} 行，每个计划提示一行（含未应答者）。",
        "变量说明 Codebook：逐列的含义、量表范围、以及该变量模型是否可见。",
        "",
        "【最关键的一列 The column that matters most】",
        "变量说明表中的「模型可见」一列。标为「否」的变量是生成过程的"
        "潜变量或标签，训练与推断时模型完全看不到，只用于评估。把它们"
        "当作输入会造成信息泄漏。",
    ])

    # ---- participant level ------------------------------------------
    hdr = (["participant_id", "split", "prompts_scheduled",
            "prompts_answered", "compliance_rate", "realised_inertia",
            "inertia_parameter", "flexibility"]
           + ["trait_" + s for s in D.FAM_SHORT]
           + ["deploy_share_" + s for s in D.FAM_SHORT]
           + ["adapt_score_" + s for s in D.FAM_SHORT]
           + ["label_" + s for s in D.FAM_SHORT]
           + ["ERQ_reappraisal", "ERQ_suppression", "DERS_total"])
    rows = [hdr]
    for i in range(n):
        m = mask[i]
        na = X[i][m, 0]
        shares = [float((used[i][m] == k).mean()) for k in range(D.K_FAM)]
        rows.append(
            [i + 1, split[i], T, int(m.sum()), round(float(m.mean()), 4),
             round(lag1(na), 4), round(float(data["inertia"][i]), 4),
             round(float(data["flex"][i]), 4)]
            + [round(float(v), 4) for v in data["trait"][i]]
            + [round(v, 4) for v in shares]
            + [round(float(v), 4) for v in data["adapt"][i]]
            + [int(v) for v in data["Y"][i]]
            + [round(float(q["ERQ_reappraisal"][i]), 3),
               round(float(q["ERQ_suppression"][i]), 3),
               round(float(q["DERS_total"][i]), 2)])
    sheet(wb, "参与者层 Participants", rows,
          widths=[14, 11, 17, 17, 15, 15, 16, 12] + [11] * 20 + [16, 16, 12])

    # ---- episode level ----------------------------------------------
    hdr = ["participant_id", "t_index", "day", "prompt_of_day",
           "answered", "deployed_family_code", "deployed_family",
           "strategy_situation_fit", "regulation_success"] + D.FEATURES
    rows = [hdr]
    for i in range(n):
        for t in range(T):
            k = int(used[i, t])
            rows.append(
                [i + 1, t + 1, t // D.N_PROMPT + 1, t % D.N_PROMPT + 1,
                 int(mask[i, t]), k + 1, D.FAMILIES[k],
                 round(float(data["fit"][i, t]), 4),
                 round(float(data["success"][i, t]), 4)]
                + [round(float(v), 4) for v in X[i, t]])
    sheet(wb, "情节层 Episodes", rows,
          widths=[14, 9, 7, 14, 10, 20, 22, 20, 19] + [15] * F)

    # ---- codebook ----------------------------------------------------
    cb = [["变量 Variable", "所在表 Sheet", "类型 Type",
           "取值范围 Range", "模型可见 Visible to model",
           "含义 Meaning"]]

    def add(v, sh, ty, rng, vis, mean):
        cb.append([v, sh, ty, rng, vis, mean])

    add("participant_id", "两表 both", "整数", "1–%d" % n, "—",
        "参与者编号 / participant identifier")
    add("split", "参与者层", "文本", "train / validation / test", "—",
        "按人划分的数据集归属，294/63/63；同一人不跨集合")
    add("prompts_scheduled", "参与者层", "整数", "%d" % T, "—",
        "计划提示数 = 14 天 × 每天 6 次")
    add("prompts_answered", "参与者层", "整数", "62–81", "是",
        "实际应答的提示数（序列长度不等）")
    add("compliance_rate", "参与者层", "小数", "0–1", "是",
        "该参与者的应答率")
    add("realised_inertia", "参与者层", "小数", "≈ −0.1–0.7", "否",
        "实测情绪惯性：瞬时负性情绪在已应答提示上的一阶自相关")
    add("inertia_parameter", "参与者层", "小数", "0.05–0.80", "否",
        "生成过程中该人的惯性参数（潜变量）")
    add("flexibility", "参与者层", "小数", "0–2", "否",
        "调节灵活性潜变量：策略部署随情境可控性变化的强度")
    add("trait_SS … trait_RM", "参与者层", "小数", "约 −3–3", "否",
        "五族策略的习惯性倾向潜变量（SS 情境选择、SM 情境修正、"
        "AD 注意分配、CC 认知改变、RM 反应调整）")
    add("deploy_share_SS … RM", "参与者层", "小数", "0–1", "否",
        "该人在已应答提示中各族策略的实际部署占比")
    add("adapt_score_SS … RM", "参与者层", "小数", "约 −1.5–2", "否",
        "适应性习惯使用的连续得分：部署频率、策略—情境契合度、情绪缓解"
        "三者的加权和")
    add("label_SS … RM", "参与者层", "0/1", "0 或 1", "否（是预测目标）",
        "评估目标：adapt_score 在全样本中位数以上记 1。五个标签各自"
        "均衡（各约 50%）")
    add("ERQ_reappraisal", "参与者层", "小数", "1–7", "否",
        "情绪调节问卷 认知重评分量表代理值（仅用于收敛效度检验，"
        "任何模型都看不到）")
    add("ERQ_suppression", "参与者层", "小数", "1–7", "否",
        "情绪调节问卷 表达抑制分量表代理值（同上）")
    add("DERS_total", "参与者层", "小数", "36–180", "否",
        "情绪调节困难量表总分代理值（同上）")
    add("t_index", "情节层", "整数", "1–%d" % T, "—",
        "该人协议内的提示序号")
    add("day", "情节层", "整数", "1–%d" % D.N_DAYS, "是",
        "协议第几天")
    add("prompt_of_day", "情节层", "整数", "1–%d" % D.N_PROMPT, "是",
        "当天第几次提示")
    add("answered", "情节层", "0/1", "0 或 1", "是",
        "是否应答。未应答的提示不进入模型，但生成过程仍记录了该时刻的"
        "真实状态")
    add("deployed_family_code / deployed_family", "情节层", "整数 / 文本",
        "1–5 / 五族名称", "否（是评估用真值）",
        "该时刻实际部署的调节策略族。这是本文 justification alignment "
        "指标的判准，也是模拟语料唯一不可替代之处")
    add("strategy_situation_fit", "情节层", "小数", "0–1", "否",
        "所用策略与该情境可控性的契合度")
    add("regulation_success", "情节层", "小数", "0–1", "否",
        "该次调节的实际效果")
    obs_note = "是（模型输入的 17 个特征之一）"
    for f in D.FEATURES:
        add(f, "情节层", "小数", "见下", obs_note, "瞬时自我报告特征")
    cb.append(["", "", "", "", "", ""])
    cb.append(["【17 个瞬时特征的量表】", "", "", "", "", ""])
    scales = [
        ("negative affect / positive affect / arousal", "1–7",
         "瞬时负性情绪、正性情绪、唤醒度"),
        ("stressor intensity", "0–1", "应激源强度"),
        ("controllability appraisal", "0–1",
         "对情境可控性的评估——本文的核心情境变量"),
        ("social presence / at home", "0 或 1", "是否有他人在场 / 是否在家"),
        ("time of day (sin) / (cos)", "−1–1", "当日时段的循环编码"),
        ("day in protocol", "0–1", "协议进程（第 1 天为 0，第 14 天为 1）"),
        ("regulatory effort", "1–7", "调节努力程度"),
        ("perceived regulation success", "1–7", "自评调节成效"),
        ("response latency", "−2–3", "作答潜伏期（对数尺度）"),
        ("item: changed the situation", "1–7", "「我改变了当时的处境」"),
        ("item: looked away or distracted", "1–7", "「我把注意力移开了」"),
        ("item: thought about it differently", "1–7",
         "「我换了个想法看这件事」"),
        ("item: kept it inside", "1–7", "「我把情绪压在心里」"),
    ]
    for name, rng, mean in scales:
        cb.append([name, "情节层", "小数", rng, obs_note, mean])
    cb.append(["", "", "", "", "", ""])
    cb.append(["【关于四个调节条目】", "", "", "", "", ""])
    cb.append(["item: … （四条）", "情节层", "小数", "1–7", obs_note,
               "四个条目在五族策略上带交叉负荷，单条并不能唯一确定所用"
               "策略——真实 EMA 自评正是如此。四条合起来才有较强的判别力："
               "论文报告的监督探针可由这些特征恢复 90.1% 的真实策略族，"
               "这正是 alignment 指标的天花板 0.904 的来源。"])
    sheet(wb, "变量说明 Codebook", cb,
          widths=[34, 14, 12, 22, 22, 62], wrap_cols=(6,))

    path = os.path.join(OUT, "EMA_raw_data.xlsx")
    wb.save(path)
    return path, len(rows) - 1


# ---------------------------------------------------------------------------
def results_workbook():
    with open(os.path.join(TAB, "results.json"), encoding="utf-8") as fh:
        R = json.load(fh)
    with open(os.path.join(TAB, "concept_collapse.json"),
              encoding="utf-8") as fh:
        COL = json.load(fh)
    with open(os.path.join(TAB, "gradcheck.json"), encoding="utf-8") as fh:
        GR = json.load(fh)

    wb = Workbook()
    wb.remove(wb.active)
    cfg, cor = R["config"], R["corpus"]

    note_sheet(wb, "说明 Readme", [
        "【本文件是什么 What this file is】",
        "论文正文中每一个数字的来源。全部读自 tables/results.json，"
        "该文件由 model/run_experiments.py 一次运行写出。",
        "正文里的数字是用 f-string 从这个 JSON 插值进去的，没有任何一个"
        "是手工填写的，所以正文与本表不可能对不上。",
        "",
        "【分析流程 Pipeline】",
        "1. model/ema_data.py        生成语料（种子 %d）" % D.SEED,
        "2. model/autodiff.py        自研 numpy 反向自动微分引擎",
        "3. model/gradcheck.py       23 项中心差分梯度检验",
        "4. model/dpapt.py           DP-APT 架构与训练循环",
        "5. model/baselines.py       5 个对比模型、AUC、ERASER 忠实度、"
        "吻合度、监督探针天花板",
        "6. model/run_experiments.py 完整实验协议 → tables/results.json",
        "7. model/concept_collapse.py 本体概念向量坍缩诊断",
        "8. analysis/figures.py      四张图",
        "9. build/build_docx.py      按期刊模板生成 Word 论文",
        "",
        "复现命令：",
        "  cd model && python3 gradcheck.py && python3 run_experiments.py "
        "&& python3 concept_collapse.py",
        "  cd ../analysis && python3 figures.py",
        "  cd ../build && python3 build_docx.py",
        "运行时间约 18 分钟（单核 CPU，无 GPU，无深度学习框架依赖）。",
        "",
        "【实验设计 Protocol】",
        "按人划分 294 训练 / 63 验证 / 63 测试，同一人不跨集合。",
        "每个模型跑 %d 个随机种子，表中括号内为跨种子标准差。"
        % len(cfg["seeds"]),
        "所有超参（含学习率、稀疏权重 λ）一律在验证集上选，测试集与任何"
        "解释指标都不参与选择。",
        "",
        "【读表时请注意 How to read the tables】",
        "Comprehensiveness ↑ 越大越好；Sufficiency ↓ 越小越好；"
        "Alignment ↑ 越大越好。",
        "Alignment 有下界也有上界：随机解释 = %.3f（各族部署边际率），"
        "同特征的监督探针 = %.3f。脱离这两个界读该列没有意义。"
        % (cor["chance_alignment"], cor["oracle_alignment"]),
    ])

    # ---- config & corpus ---------------------------------------------
    rows = [["项目 Item", "值 Value", "说明 Note"]]
    conf = [
        ("参与者数 participants", cfg["n_participants"], ""),
        ("训练 / 验证 / 测试", "%d / %d / %d" % (
            cfg["n_train"], cfg["n_val"], cfg["n_test"]), "按人划分"),
        ("计划提示数 scheduled prompts", cfg["t_max"], "14 天 × 6 次"),
        ("特征数 features", cfg["f_dim"], ""),
        ("策略族数 families", cfg["n_families"], ""),
        ("表示维度 d_model", cfg["d_model"], ""),
        ("图传播层数 layers", cfg["layers"], ""),
        ("注意力头数 heads", cfg["heads"], "仅注意力变体使用"),
        ("批大小 batch", cfg["batch"], "以参与者计"),
        ("最大轮数 epochs", cfg["epochs"], "验证集早停，耐心 20"),
        ("随机种子 seeds", ", ".join(str(s) for s in cfg["seeds"]), ""),
        ("稀疏权重 λ", cfg["lam"], "所提模型无情节注意力，故取 0"),
        ("解释取前 k 个情节", cfg["topk"], ""),
        ("实际应答率 compliance", round(cfg["compliance"], 4), ""),
    ]
    for a, b, c in conf:
        rows.append([a, b, c])
    rows.append(["", "", ""])
    rows.append(["【语料描述统计 Corpus descriptives】", "", ""])
    corp = [
        ("情绪惯性 均值 (SD)", "%.3f (%.3f)" % (
            cor["inertia_mean"], cor["inertia_sd"]),
         "瞬时负性情绪一阶自相关；文献社区样本约 0.35"),
        ("已应答提示数 均值", "%.1f" % cor["prompts_mean"],
         "范围 %d–%d" % (cor["prompts_min"], cor["prompts_max"])),
        ("ERQ 重评 M (SD)", "%.2f (%.2f)" % tuple(cor["erq_reap"]),
         "已发表值 4.9 (0.9)"),
        ("ERQ 抑制 M (SD)", "%.2f (%.2f)" % tuple(cor["erq_supp"]),
         "已发表值 3.4 (1.1)"),
        ("DERS 总分 M (SD)", "%.1f (%.1f)" % tuple(cor["ders"]),
         "已发表值 80 (20)"),
        ("五族部署占比", ", ".join("%.3f" % v for v in cor["deployment"]),
         "SS, SM, AD, CC, RM"),
        ("五个标签阳性率", ", ".join("%.2f" % v for v in cor["prevalence"]),
         "按中位数二分，故各约 0.5"),
        ("随机解释吻合度（下界）", "%.3f" % cor["chance_alignment"],
         "各族部署边际率的平均"),
        ("监督探针吻合度（上界）", "%.3f" % cor["oracle_alignment"],
         "多项 logistic 探针，情节级正确率 %.3f" % cor["oracle_accuracy"]),
    ]
    for a, b, c in corp:
        rows.append([a, b, c])
    rows.append(["", "", ""])
    rows.append(["【梯度检验 Gradient check】", "", ""])
    rows.append(["检验项数", GR["n_checks"], "中心差分对照自动微分"])
    rows.append(["最大相对偏差", "%.2e" % GR["max_relative_deviation"],
                 "全部通过" if GR["all_passed"] else "有未通过项"])
    rows.append(["", "", ""])
    rows.append(["【本体概念向量坍缩诊断 Concept collapse】", "", ""])
    for k, v in COL.items():
        rows.append([k, "平均 |cos| %.3f，最近一对 %.3f" % (
            v["mean_abs_cosine"], v["max_abs_cosine"]),
            "无残差连接时最近一对几乎重合，探测器无法区分这两族"])
    sheet(wb, "配置与语料 Config", rows, widths=[34, 30, 52],
          wrap_cols=(3,))

    # ---- Table 1 ------------------------------------------------------
    order = ["Aggregated logistic regression", "Gated recurrent encoder",
             "Self-attentive encoder", "Temporal graph encoder",
             "Attentive diagnostic model", "DP-APT (proposed)"]
    rows = [["模型 Model", "AUC-ROC", "SD", "AUC-PR", "SD"]]
    for k in order:
        m = R["models"][k]
        rows.append([k, round(m["auc_roc"], 4), round(m["auc_roc_sd"], 4),
                     round(m["auc_pr"], 4), round(m["auc_pr_sd"], 4)])
    sheet(wb, "表1 预测性能", rows, widths=[34, 11, 9, 11, 9])

    # ---- per-family ---------------------------------------------------
    rows = [["模型 Model"] + ["AUC-ROC " + f for f in D.FAM_SHORT]]
    for k in order:
        rows.append([k] + [round(v, 4)
                           for v in R["models"][k]["roc_per_family"]])
    sheet(wb, "表1附 逐族AUC", rows, widths=[34] + [14] * 5)

    # ---- Table 2 ------------------------------------------------------
    rows = [["解释 Model (explanation method)",
             "Comprehensiveness ↑", "SD", "Sufficiency ↓", "SD",
             "Alignment ↑", "SD"]]

    def mrow(label, m, keys=("comprehensiveness", "sufficiency",
                             "alignment")):
        out = [label]
        for key in keys:
            out += [round(m[key], 4), round(m[key + "_sd"], 4)]
        return out

    for k, lab in (
            ("Gated recurrent encoder",
             "Gated recurrent encoder + integrated gradients"),
            ("Self-attentive encoder",
             "Self-attentive encoder + integrated gradients"),
            ("Attentive diagnostic model",
             "Attentive diagnostic model (score decomposition)"),
            ("Temporal graph encoder",
             "Temporal graph encoder (score decomposition)")):
        rows.append(mrow(lab, R["models"][k]))
    av = R["ablation"]["with attention over episodes"]
    rows.append(mrow("DP-APT with attention (attention distribution)", av,
                     keys=("comprehensiveness_attention",
                           "sufficiency_attention",
                           "alignment_attention")))
    rows.append(mrow("DP-APT (proposed, score decomposition)",
                     R["models"]["DP-APT (proposed)"]))
    rows.append(["Chance level (marginal deployment rate)", "—", "—",
                 "—", "—", round(cor["chance_alignment"], 4), "—"])
    rows.append(["Oracle ceiling (supervised episode probe)", "—", "—",
                 "—", "—", round(cor["oracle_alignment"], 4), "—"])
    sheet(wb, "表2 解释质量", rows, widths=[48, 19, 9, 15, 9, 13, 9])

    # ---- Table 3 ------------------------------------------------------
    abl = ["without the ontology parser", "without the temporal graph",
           "without the item anchoring term",
           "with attention over episodes", "full model"]
    pretty = {"without the ontology parser": "w/o RPOP 去本体解析器"
                                             "（改用自由概念嵌入）",
              "without the temporal graph": "w/o TAGN 去时序图"
                                            "（改用门控序列编码器）",
              "without the item anchoring term": "w/o anchoring 去条目"
                                                 "锚定项（μ = 0）",
              "with attention over episodes": "+ attention 加情节注意力"
                                              "（即在情节维归一化）",
              "full model": "Full DP-APT 完整模型"}
    rows = [["变体 Variant", "AUC-ROC", "SD", "Sufficiency ↓", "SD",
             "Alignment ↑", "SD", "验证集交叉熵 val BCE", "SD"]]
    for k in abl:
        a = R["ablation"][k]
        rows.append([pretty[k],
                     round(a["auc_roc"], 4), round(a["auc_roc_sd"], 4),
                     round(a["sufficiency"], 4),
                     round(a["sufficiency_sd"], 4),
                     round(a["alignment"], 4), round(a["alignment_sd"], 4),
                     round(a["val_bce"], 4), round(a["val_bce_sd"], 4)])
    sheet(wb, "表3 消融", rows,
          widths=[42, 11, 9, 15, 9, 13, 9, 20, 9])

    # ---- Table 4 ------------------------------------------------------
    names = {"ERQ_reappraisal": "ERQ 认知重评 reappraisal",
             "ERQ_suppression": "ERQ 表达抑制 suppression",
             "DERS_total": "DERS 总分 total"}
    rows = [["模型输出 Model output", "效标 Criterion", "r", "p",
             "N", "显著性 Significance"]]
    for lab, v in R["validity"].items():
        p = v["p"]
        rows.append([lab, names[v["criterion"]], round(v["r"], 4),
                     round(p, 5), v["n"],
                     "p < .05" if p < 0.05 else "不显著 n.s."])
    sheet(wb, "表4 收敛效度", rows, widths=[30, 28, 10, 12, 8, 20])

    # ---- sweep --------------------------------------------------------
    rows = [["稀疏权重 λ", "AUC-ROC", "SD", "Comprehensiveness ↑", "SD",
             "Sufficiency ↓", "Alignment ↑", "SD",
             "注意力自身的 Alignment", "SD", "验证集交叉熵"]]
    for s in R["sparsity_sweep"]:
        rows.append([s["lam"], round(s["auc_roc"], 4),
                     round(s["auc_roc_sd"], 4),
                     round(s["comprehensiveness"], 4),
                     round(s["comprehensiveness_sd"], 4),
                     round(s["sufficiency"], 4),
                     round(s["alignment"], 4),
                     round(s["alignment_sd"], 4),
                     round(s["alignment_attention"], 4),
                     round(s["alignment_attention_sd"], 4),
                     round(s["val_bce"], 4)])
    rows.append(["", "", "", "", "", "", "", "", "", "", ""])
    rows.append(["读法：comprehensiveness 单调上升，AUC 明显下降，"
                 "alignment 非单调且变动量与跨种子标准差同量级——"
                 "所以论文只主张「稀疏化买不到正确性」，没有主张"
                 "「稀疏化降低正确性」。", "", "", "", "", "", "", "",
                 "", "", ""])
    ws = sheet(wb, "稀疏权重扫描 Sweep", rows,
               widths=[13, 11, 9, 21, 9, 15, 13, 9, 22, 9, 16])
    ws.cell(row=len(rows), column=1).alignment = WRAP

    # ---- criterion agreement -----------------------------------------
    ca = R["criterion_agreement"]
    rows = [["项目 Item", "值 Value"],
            ["参与相关的模型数 n", ca["n"]],
            ["Spearman ρ（comprehensiveness 对 alignment）",
             round(ca["spearman_rho"], 4)],
            ["p", round(ca["p"], 4)],
            ["", ""],
            ["这是论文的核心发现：现行忠实度指标与「解释是否指对时刻」"
             "几乎无关。ρ 近于 0，且两端反转——擦除得分最高的模型吻合度"
             "最低。", ""]]
    ws = sheet(wb, "核心发现 两指标相关", rows, widths=[52, 16])
    ws.cell(row=6, column=1).alignment = WRAP

    path = os.path.join(OUT, "EMA_analysis_results.xlsx")
    wb.save(path)
    return path


# ---------------------------------------------------------------------------
def csv_copies(data, tr, va, te):
    """Plain-text copies of both tables, for anything that is not Excel."""
    import csv
    n, T, _ = data["X_raw"].shape
    X, mask, used = data["X_raw"], data["mask"], data["used"]
    split = np.empty(n, dtype=object)
    split[tr], split[va], split[te] = "train", "validation", "test"
    q = data["quest"]

    p1 = os.path.join(OUT, "participants.csv")
    with open(p1, "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.writer(fh)
        w.writerow(["participant_id", "split", "prompts_answered"]
                   + ["trait_" + s for s in D.FAM_SHORT]
                   + ["adapt_" + s for s in D.FAM_SHORT]
                   + ["label_" + s for s in D.FAM_SHORT]
                   + ["ERQ_reappraisal", "ERQ_suppression", "DERS_total"])
        for i in range(n):
            w.writerow([i + 1, split[i], int(mask[i].sum())]
                       + ["%.4f" % v for v in data["trait"][i]]
                       + ["%.4f" % v for v in data["adapt"][i]]
                       + [int(v) for v in data["Y"][i]]
                       + ["%.3f" % q["ERQ_reappraisal"][i],
                          "%.3f" % q["ERQ_suppression"][i],
                          "%.2f" % q["DERS_total"][i]])

    p2 = os.path.join(OUT, "episodes.csv")
    with open(p2, "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.writer(fh)
        w.writerow(["participant_id", "t_index", "day", "prompt_of_day",
                    "answered", "deployed_family"] + D.FEATURES)
        for i in range(n):
            for t in range(T):
                w.writerow([i + 1, t + 1, t // D.N_PROMPT + 1,
                            t % D.N_PROMPT + 1, int(mask[i, t]),
                            D.FAMILIES[int(used[i, t])]]
                           + ["%.4f" % v for v in X[i, t]])
    return p1, p2


# ---------------------------------------------------------------------------
def main():
    print("generating the corpus (seed %d) ..." % D.SEED)
    data = D.generate()
    tr, va, te = D.splits()
    print("writing the raw-data workbook ...")
    p_raw, n_ep = raw_workbook(data, tr, va, te)
    print("  %s  (%d episode rows)" % (p_raw, n_ep))
    print("writing the results workbook ...")
    p_res = results_workbook()
    print("  %s" % p_res)
    print("writing csv copies ...")
    for p in csv_copies(data, tr, va, te):
        print("  %s" % p)
    print("done")


if __name__ == "__main__":
    main()
