"""Section 2 (basic SBOA) and Section 3 (proposed MSSBOA): prose + verified equations."""
from docx.enum.text import WD_ALIGN_PARAGRAPH as AL
from docx.shared import Pt, Cm
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

def section2(P):
    e={}
    P.heading("2. Secretary Bird Optimization Algorithm",1)
    P.body([
        ('text',"SBOA is a population-based metaheuristic inspired by the survival behavior of secretary "
                "birds in the African savanna "),
        ('cite',['sboa']),
        ('text',". The algorithm starts from a randomly generated population and improves the candidate "
                "solutions through an exploration phase that mimics the three-stage strategy of hunting "
                "snakes and an exploitation phase that mimics two strategies of escaping predators. When "
                "the stopping criterion is met, SBOA outputs the best solution. The detailed formulation "
                "is described as follows.")
    ])

    P.heading("2.1. Initialization",2)
    P.body([('text',"Like most metaheuristics, SBOA initializes a population of "),('math','N'),
            ('text'," candidate solutions that are uniformly distributed within the search space. "
                    "Each individual is generated by the following equation.")])
    e['init']=P.equation(r"x_{i,j}=lb_{j}+r\cdot\left(ub_{j}-lb_{j}\right),\quad i=1,2,\dots,N,\ \ j=1,2,\dots,D")
    P.body([('text',"where "),('math','x_{i,j}'),('text'," denotes the "),('math','j'),
            ('text',"-th dimension of the "),('math','i'),('text',"-th individual, "),('math','r'),
            ('text'," is a random number in "),('math','[0,1]'),('text',", "),('math','lb_{j}'),
            ('text'," and "),('math','ub_{j}'),('text'," are the lower and upper bounds of the "),
            ('math','j'),('text',"-th dimension, "),('math','N'),('text'," is the population size and "),
            ('math','D'),('text'," is the dimension of the problem. After initialization, all "
            "individuals are evaluated and sorted according to their fitness; a minimization problem is "
            "considered in this paper, so individuals with smaller fitness are ranked higher.")])

    P.heading("2.2. Exploration phase: hunting strategy",2)
    P.body([('text',"In the wild, a secretary bird spends a long time searching for prey such as snakes "
                    "before launching a rapid attack. SBOA divides the exploration phase into three "
                    "successive stages according to the iteration counter. In the first stage (searching "
                    "for prey), the individual is updated by a differential perturbation of two randomly "
                    "selected individuals, as in Equation (2).")])
    e['s1']=P.equation(r"x_{i,j}^{new,P1}=x_{i,j}+\left(x_{rand_{1},j}-x_{rand_{2},j}\right)\cdot R_{1}")
    P.body([('text',"where "),('math','x_{rand_{1},j}'),('text'," and "),('math','x_{rand_{2},j}'),
            ('text'," are the positions of two randomly selected individuals and "),('math','R_{1}'),
            ('text'," is a random number in "),('math','[0,1]'),
            ('text',". In the second stage (consuming prey), the individual approaches the best "
                    "individual under a Brownian-motion perturbation, as in Equation (3).")])
    e['s2']=P.equation(r"x_{i,j}^{new,P1}=X_{best,j}+\exp\!\left[\left(\tfrac{t}{T}\right)^{4}\right]\cdot\left(R_{B}-0.5\right)\cdot\left(X_{best,j}-x_{i,j}\right)")
    P.body([('text',"where "),('math','X_{best,j}'),('text'," is the "),('math','j'),
            ('text',"-th dimension of the best individual, "),('math','t'),('text'," and "),('math','T'),
            ('text'," are the current and maximum numbers of iterations, and "),('math','R_{B}'),
            ('text'," is a Brownian-motion random vector drawn from the standard normal distribution. "
                    "In the third stage (attacking prey), the individual performs a Lévy flight around "
                    "the best individual, as in Equation (4).")])
    e['s3']=P.equation(r"x_{i,j}^{new,P1}=X_{best,j}+\left(1-\tfrac{t}{T}\right)^{2t/T}\cdot x_{i,j}\cdot R_{L}")
    P.body([('text',"where "),('math',r'R_{L}=0.5\cdot Levy(D)'),('text'," is a Lévy-flight step vector. "
                    "The three stages are selected by the iteration counter: the first stage is used when "),
            ('math','t<T/3'),('text',", the second stage when "),('math',r'T/3\le t<2T/3'),
            ('text',", and the third stage when "),('math',r't\ge 2T/3'),
            ('text',". After each update, a greedy selection is performed, as in Equation (5).")])
    e['greedy']=P.equation(r"X_{i}=\begin{cases}X_{i}^{new}, & f\!\left(X_{i}^{new}\right)<f\!\left(X_{i}\right)\\[2pt] X_{i}, & \text{otherwise}\end{cases}")
    P.body([('text',"where "),('math',r'f(\cdot)'),('text'," is the objective function. The greedy "
                    "selection guarantees that the population never deteriorates.")])

    P.heading("2.3. Exploitation phase: escape strategy",2)
    P.body([('text',"Secretary birds are threatened by predators such as eagles and must escape to "
                    "survive. SBOA models two escape strategies and selects one of them at random in "
                    "each iteration. When "),('math','r<0.5'),('text',", the first strategy "),
            ('math','C_{1}'),('text'," (camouflage by the environment) is used, as in Equation (6).")])
    e['c1']=P.equation(r"x_{i,j}^{new,P2}=X_{best,j}+\left(1-\tfrac{t}{T}\right)^{2}\cdot\left(2R_{B}-1\right)\cdot x_{i,j}")
    P.body([('text',"where "),('math','r'),('text'," is a random number in "),('math','[0,1]'),
            ('text'," and "),('math','R_{B}'),('text'," is a random vector in "),('math','[0,1]'),
            ('text',". Otherwise, the second strategy "),('math','C_{2}'),
            ('text'," (fleeing toward a safe place) is used, as in Equation (7).")])
    e['c2']=P.equation(r"x_{i,j}^{new,P2}=x_{i,j}+R_{2}\cdot\left(x_{random,j}-K\cdot x_{i,j}\right)")
    P.body([('text',"where "),('math','R_{2}'),('text'," is a random vector in "),('math','[0,1]'),
            ('text',", "),('math','x_{random,j}'),('text'," is a randomly selected individual and "),
            ('math',r'K=\mathrm{round}(1+rand)\in\{1,2\}'),('text',". The Lévy flight used in Equation (4) "
                    "is generated by the Mantegna algorithm "),('cite',['mantegna','cuckoo']),
            ('text',", as in Equation (8).")])
    e['levy']=P.equation(r"Levy(D)=\frac{u}{\left|v\right|^{1/\beta}},\quad \sigma=\left[\frac{\Gamma(1+\beta)\sin\!\left(\pi\beta/2\right)}{\Gamma\!\left(\frac{1+\beta}{2}\right)\beta\,2^{(\beta-1)/2}}\right]^{1/\beta}")
    P.body([('text',"where "),('math',r'u\sim N(0,\sigma^{2})'),('text'," and "),('math','v\sim N(0,1)'),
            ('text'," are normally distributed, "),('math','\\Gamma'),('text'," is the Gamma function and "),
            ('math',r'\beta=1.5'),('text'," is a constant.")])
    return e

def _algo_box(P, title, lines):
    """Pseudo-code box: bordered single-column table with a title row and numbered lines."""
    t=P.doc.add_table(rows=1,cols=1); t.alignment=WD_TABLE_ALIGNMENT.CENTER
    # borders top/bottom + header bottom
    tbl=t._tbl; borders=OxmlElement('w:tblBorders')
    def bd(tag,sz,val="single"):
        e=OxmlElement('w:'+tag); e.set(qn('w:val'),val); e.set(qn('w:sz'),str(sz))
        e.set(qn('w:space'),'0'); e.set(qn('w:color'),'000000'); return e
    for tg in ('top','bottom'): borders.append(bd(tg,10))
    for tg in ('left','right','insideH','insideV'): borders.append(bd(tg,0,'none'))
    t._tbl.tblPr.append(borders)
    hp=t.rows[0].cells[0].paragraphs[0]; r=hp.add_run(title); r.bold=True; r.font.size=Pt(9)
    # header bottom border
    tcPr=t.rows[0].cells[0]._tc.get_or_add_tcPr(); tcb=OxmlElement('w:tcBorders')
    b=OxmlElement('w:bottom'); b.set(qn('w:val'),'single'); b.set(qn('w:sz'),'8'); b.set(qn('w:space'),'0'); b.set(qn('w:color'),'000000')
    tcb.append(b); tcPr.append(tcb)
    cell=t.add_row().cells[0]
    cell.paragraphs[0]._p.getparent().remove(cell.paragraphs[0]._p)
    for ln in lines:
        p=cell.add_paragraph(); p.paragraph_format.space_after=Pt(0); p.paragraph_format.line_spacing=1.0
        r=p.add_run(ln); r.font.size=Pt(8.5); r.font.name="Consolas"
    return t

def section3(P, e2):
    e={}
    P.heading("3. Proposed Multi-Strategy Secretary Bird Optimization Algorithm",1)
    P.body([('text',"Although SBOA performs well on many problems, it still has shortcomings that limit "
                    "its search efficiency. The random initialization cannot guarantee a uniform coverage "
                    "of the search space, which weakens the initial population diversity. The search "
                    "relies heavily on the current best individual, so the population is prone to "
                    "premature convergence and easily trapped in local optima, and the transition between "
                    "exploration and exploitation is not fully balanced. To overcome these limitations, "
                    "this section proposes a multi-strategy SBOA (MSSBOA) that incorporates three "
                    "improvement strategies: good point set initialization, lens opposition-based learning "
                    "and adaptive Cauchy–Gaussian mutation. Each strategy is described in detail below, "
                    "followed by the overall framework, the pseudo-code and the complexity analysis.")])

    P.heading("3.1. Good point set initialization (GPSI)",2)
    P.body([('text',"The distribution of the initial population strongly affects the convergence of a "
                    "metaheuristic. A uniformly distributed initial population enhances diversity and "
                    "enables the algorithm to explore the solution space more comprehensively. The good "
                    "point set, derived from number theory "),('cite',['goodpoint']),
            ('text',", is a low-discrepancy sequence whose deviation is asymptotically lower than that of "
                    "pseudo-random sampling, and it has been successfully used to initialize swarm "
                    "algorithms "),('cite',['sandcat']),
            ('text',". For a "),('math','D'),('text',"-dimensional problem, let "),('math','p'),
            ('text'," be the smallest prime satisfying "),('math',r'(p-3)/2\ge D'),
            ('text',". The good point is constructed by Equation (9).")])
    e['gps']=P.equation(r"r_{k}=\left\{2\cos\!\left(\frac{2\pi k}{p}\right)\right\},\quad k=1,2,\dots,D")
    P.body([('text',"where "),('math',r'\{\cdot\}'),('text'," denotes the fractional part. The "),
            ('math','i'),('text',"-th individual is then mapped to the search space by Equation (10).")])
    e['gpsmap']=P.equation(r"x_{i,j}=lb_{j}+\left\{r_{j}\cdot i\right\}\cdot\left(ub_{j}-lb_{j}\right),\quad i=1,2,\dots,N")
    P.body([('text',"Compared with random initialization, the good point set yields a more even spread of "
                    "the initial population that is independent of the dimension, providing the algorithm "
                    "with a better starting point for the subsequent search.")])

    P.heading("3.2. Lens opposition-based learning (LOBL)",2)
    P.body([('text',"Opposition-based learning evaluates a candidate solution together with its opposite "
                    "and keeps the better one, which effectively enlarges the explored region "),
            ('cite',['obl','qobl']),
            ('text',". Lens opposition-based learning extends this idea using the principle of convex-lens "
                    "imaging: an object placed on one side of a lens forms an image on the other side, "
                    "which corresponds to a refracted reverse solution with a tunable scaling factor "),
            ('cite',['lensobl']),
            ('text',". The lens-refracted solution is computed by Equation (11).")])
    e['lobl']=P.equation(r"x_{j}^{*}=\frac{lb_{j}+ub_{j}}{2}+\frac{lb_{j}+ub_{j}}{2k}-\frac{x_{j}}{k}")
    P.body([('text',"where "),('math','x_{j}^{*}'),('text'," is the refracted solution and "),('math','k'),
            ('text'," is an adjustment factor. When "),('math','k=1'),
            ('text',", Equation (11) degenerates into the standard opposition-based learning. To balance "
                    "the global and local search, a dynamically increasing factor is adopted, as in "
                    "Equation (12).")])
    e['k']=P.equation(r"k=\left(1+\left(\frac{t}{T}\right)^{1/2}\right)^{10}")
    P.body([('text',"A small "),('math','k'),('text'," in the early stage produces a refracted solution far "
                    "from the current one, which favors exploration, while a large "),('math','k'),
            ('text'," in the later stage keeps the refracted solution close to the current one, which "
                    "favors exploitation. In MSSBOA, the lens opposition-based learning is applied only to "
                    "the inferior individuals (the worst 30% of the population) at the end of each "
                    "iteration. As illustrated in Figure 2, this helps the population jump out of local "
                    "optima while the greedy selection protects the elite individuals.")])
    P.figure("fig02_lensobl.png","Schematic of the lens opposition-based learning strategy.", width_cm=12.0)

    P.heading("3.3. Adaptive Cauchy–Gaussian mutation (ACGM)",2)
    P.body([('text',"To further balance exploration and exploitation and to help the best individual "
                    "escape local optima, an adaptive Cauchy–Gaussian mutation is imposed on the best "
                    "individual "),('cite',['fep','sboa_cg']),
            ('text',". The Cauchy distribution has heavier tails than the Gaussian distribution and thus "
                    "generates larger perturbations for global exploration, whereas the Gaussian "
                    "distribution produces small perturbations for local refinement. The mutation is "
                    "defined by Equation (13).")])
    e['acgm']=P.equation(r"X_{best}^{new}=X_{best}\cdot\left(1+\lambda_{1}\,\mathrm{Cauchy}(0,1)+\lambda_{2}\,N(0,1)\right)")
    P.body([('text',"where "),('math',r'\mathrm{Cauchy}(0,1)'),('text'," is a standard Cauchy random number, "),
            ('math','N(0,1)'),('text'," is a standard normal random number, and "),('math',r'\lambda_{1}'),
            ('text'," and "),('math',r'\lambda_{2}'),(
            'text'," are adaptive weights defined by Equation (14).")])
    e['lam']=P.equation(r"\lambda_{1}=1-\frac{t^{2}}{T^{2}},\qquad \lambda_{2}=\frac{t^{2}}{T^{2}}")
    P.body([('text',"In the early iterations "),('math',r'\lambda_{1}'),('text'," is large, so the "
                    "Cauchy-dominated perturbation enhances global exploration; in the later iterations "),
            ('math',r'\lambda_{2}'),('text'," becomes large, so the Gaussian-dominated perturbation "
                    "strengthens local exploitation. The mutated solution replaces the best individual "
                    "only when it is better, according to the greedy rule in Equation (5).")])

    P.heading("3.4. The framework of MSSBOA",2)
    P.body([('text',"MSSBOA is obtained by integrating the three improvement strategies into the basic "
                    "SBOA. The good point set initialization (GPSI) generates a high-quality initial "
                    "population; the hunting and escape strategies of SBOA drive the main search; the "
                    "lens opposition-based learning (LOBL) refreshes the inferior individuals to escape "
                    "local optima; and the adaptive Cauchy–Gaussian mutation (ACGM) perturbs the best "
                    "individual to balance exploration and exploitation. The pseudo-code of MSSBOA is "
                    "given in Algorithm 1, and the corresponding flowchart is shown in Figure 3.")])
    _algo_box(P,"Algorithm 1  Multi-Strategy Secretary Bird Optimization Algorithm (MSSBOA)",[
        "1:  Initialize population X using good point set (Eq. (9)-Eq. (10))   // GPSI",
        "2:  Set t = 0, maximum iteration T, population size N",
        "3:  Evaluate fitness of X and record the best individual X_best",
        "4:  while t < T do",
        "5:      for each individual i do",
        "6:          if t < T/3 then  update X_i by Eq. (2)            // searching for prey",
        "7:          else if t < 2T/3 then  update X_i by Eq. (3)      // consuming prey",
        "8:          else  update X_i by Eq. (4)                       // attacking prey",
        "9:          end if; perform greedy selection by Eq. (5)",
        "10:         if r < 0.5 then  update X_i by Eq. (6)            // escape C1",
        "11:         else  update X_i by Eq. (7)                       // escape C2",
        "12:         end if; perform greedy selection by Eq. (5)",
        "13:     end for",
        "14:     Apply lens opposition-based learning to the worst 30% by Eq. (11)-Eq. (12)  // LOBL",
        "15:     Apply adaptive Cauchy-Gauss mutation to X_best by Eq. (13)-Eq. (14)         // ACGM",
        "16:     Update X_best; t = t + 1",
        "17: end while",
        "18: return the best individual X_best",
    ])
    P.figure("fig03_flowchart.png","The flowchart of MSSBOA.", width_cm=11.5)

    P.heading("3.5. Complexity analysis of MSSBOA",2)
    P.body([('text',"The computational complexity of MSSBOA is analyzed in terms of time and space "
                    "complexity. Let "),('math','N'),('text'," be the population size, "),('math','D'),
            ('text'," the dimension and "),('math','T'),('text'," the maximum number of iterations. "
                    "According to its original literature, the time complexity of the basic SBOA is "),
            ('math','O(N\\cdot D\\cdot T)'),('text'," and its space complexity is "),('math','O(N\\cdot D)'),
            ('text',".")])
    P.body([('text',"For MSSBOA, the good point set initialization has the same complexity as random "
                    "initialization, namely "),('math','O(N\\cdot D)'),
            ('text',", and therefore does not change the order of complexity. The lens opposition-based "
                    "learning is applied to a fixed fraction of the population, with complexity "),
            ('math','O(N\\cdot D)'),('text'," per iteration, and the adaptive Cauchy–Gaussian mutation "
                    "acts only on the best individual with complexity "),('math','O(D)'),
            ('text',". Hence the overall time complexity of MSSBOA remains "),('math','O(N\\cdot D\\cdot T)'),
            ('text',", the same as the basic SBOA. Regarding space, MSSBOA only stores the population "
                    "matrix and a few temporary vectors for the refracted and mutated solutions, so its "
                    "space complexity is still "),('math','O(N\\cdot D)'),
            ('text',". In summary, the three improvement strategies enhance the performance of SBOA "
                    "without increasing its order of computational complexity.")])
    return e
