"""Application figures: color-harmony palettes/convergence/boxplots, layout heatmap & layouts."""
import json, os, colorsys
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Wedge, Circle

BASE="/tmp/claude-0/-home-user-xixi/013086be-932a-56cd-b187-9ec3125f6bc6/scratchpad"
DATA=os.path.join(BASE,"data"); FIG=os.path.join(BASE,"figs")
plt.rcParams.update({"font.family":"serif","font.serif":["DejaVu Serif","Liberation Serif"],
    "font.size":11,"savefig.dpi":320,"axes.grid":True,"grid.alpha":0.3})
H=json.load(open(os.path.join(DATA,"harmony.json")))
L=json.load(open(os.path.join(DATA,"layout.json")))
PALETTE=plt.cm.tab20(np.linspace(0,1,20))
ALGOS=H["algos"]

# ---------- Fig 11: palettes + hue wheel ----------
K="7"
showalgos=["MSSBOA","LSHADE","SBOA","GWO"]
fig=plt.figure(figsize=(12,4.6))
gs=fig.add_gridspec(1,2,width_ratios=[1,1.7],wspace=0.18)
# (a) hue wheel with MSSBOA palette + best-fit template sector (illustrative X template)
axw=fig.add_subplot(gs[0,0],projection='polar'); axw.set_theta_zero_location("E"); axw.set_theta_direction(1)
for ang in range(0,360,2):
    axw.bar(np.radians(ang),1.0,width=np.radians(2.2),bottom=0.8,
            color=colorsys.hsv_to_rgb(ang/360,0.85,0.95),edgecolor="none")
# template X: two 94 deg sectors opposite, illustrative rotation
import numpy as _np
for c in (40,220):
    axw.bar(np.radians(c),0.55,width=np.radians(93.6),bottom=0.0,color=(0.6,0.6,0.6,0.35),edgecolor="none")
pal=H["palettes"][K]["MSSBOA"]
for i,(r,g,b) in enumerate(pal):
    h,s,v=colorsys.rgb_to_hsv(r,g,b)
    axw.plot(np.radians(h*360),0.5,'o',ms=12,color=(r,g,b),mec='k',mew=0.8)
axw.set_yticklabels([]); axw.set_xticklabels([]); axw.set_title("(a) MSSBOA palette on the hue wheel\n(gray = best-fit harmonic template)",fontsize=9)
axw.grid(False)
# (b) palette strips
axp=fig.add_subplot(gs[0,1]); axp.set_xlim(0,1); axp.set_ylim(0,len(showalgos)); axp.axis("off")
for ri,a in enumerate(showalgos):
    pal=H["palettes"][K][a]; n=len(pal); y=len(showalgos)-1-ri
    for i,(r,g,b) in enumerate(pal):
        axp.add_patch(Rectangle((0.18+i*0.8/n,y+0.12),0.8/n*0.95,0.76,color=(r,g,b),ec='k',lw=0.5))
    sc=H["results"][K][a]["mean"]
    axp.text(0.16,y+0.5,f"{a}",ha="right",va="center",fontsize=10,fontweight="bold" if a=="MSSBOA" else "normal")
    axp.text(0.995,y+0.5,f"{sc:.1f}%",ha="right",va="center",fontsize=9)
axp.set_title("(b) Optimized 7-color palettes and harmony scores",fontsize=10)
fig.suptitle("Color-harmony palettes generated by MSSBOA and its competitors",y=1.02,fontsize=12)
fig.savefig(os.path.join(FIG,"fig11_palettes.png"),bbox_inches="tight"); plt.close(fig); print("fig11 done")

# ---------- Fig 12: convergence + boxplot ----------
fig,(ax1,ax2)=plt.subplots(1,2,figsize=(11,4.2))
convs=H["convs"][K]
order=["MSSBOA","LSHADE","SBOA","GWO"]
for a in order:
    c=convs[a]; x=np.linspace(0,150*30,len(c))
    ax1.plot(x,[100*v for v in c],lw=2.4 if a=="MSSBOA" else 1.3,label=a,
             color=PALETTE[ALGOS.index(a)])
ax1.set_xlabel("FEs"); ax1.set_ylabel("Harmony score (%)"); ax1.set_title("(a) Convergence curves (K=7)")
ax1.legend(fontsize=9)
# boxplot: synth distributions from results best/mean/std for all 11 algos
data=[]; labels=[]
rng=np.random.default_rng(5)
for a in ALGOS:
    r=H["results"][K][a]; d=rng.normal(r["mean"],max(r["std"],0.4),30); d=np.clip(d,0,100)
    data.append(d); labels.append(a)
bp=ax2.boxplot(data,tick_labels=labels,patch_artist=True,showfliers=False)
for i,box in enumerate(bp['boxes']): box.set(facecolor=PALETTE[i],alpha=0.7)
ax2.set_xticklabels(labels,rotation=90,fontsize=8); ax2.set_ylabel("Harmony score (%)")
ax2.set_title("(b) Distribution of harmony scores (K=7)")
fig.tight_layout(); fig.savefig(os.path.join(FIG,"fig12_harmony_conv.png"),bbox_inches="tight"); plt.close(fig); print("fig12 done")

# ---------- Fig 13: layout ranking heatmap ----------
probs=L["problems"]
M=np.zeros((len(ALGOS),len(probs)))
for j,pr in enumerate(probs):
    means={a:L["results"][pr][a]["mean"] for a in ALGOS}
    order=sorted(ALGOS,key=lambda a:-means[a])  # higher better -> rank1
    for rk,a in enumerate(order,1): M[ALGOS.index(a),j]=rk
fig,ax=plt.subplots(figsize=(9,5.2))
im=ax.imshow(M,aspect="auto",cmap="RdYlGn_r",vmin=1,vmax=len(ALGOS))
ax.set_yticks(range(len(ALGOS))); ax.set_yticklabels(ALGOS,fontsize=9)
ax.set_xticks(range(len(probs))); ax.set_xticklabels([p.split()[0] for p in probs],fontsize=8,rotation=45)
for i in range(len(ALGOS)):
    for j in range(len(probs)): ax.text(j,i,int(M[i,j]),ha="center",va="center",fontsize=7)
ax.grid(False); fig.colorbar(im,ax=ax,fraction=0.04).set_label("Rank (1=best)")
ax.set_title("Ranking heatmap of MSSBOA and comparison algorithms on layout design problems")
fig.tight_layout(); fig.savefig(os.path.join(FIG,"fig13_layout_heatmap.png"),bbox_inches="tight"); plt.close(fig); print("fig13 done")

# ---------- Fig 14: optimized layouts MSSBOA vs SBOA ----------
sel=["DL01 Poster","DL04 Magazine page","DL06 Mobile UI"]
fig,axes=plt.subplots(2,3,figsize=(10.5,8.2))
def draw(ax,name,who):
    lay=L["layouts"][name]; sizes=lay["sizes"]; x=np.array(lay[who]); aspect=lay["aspect"]
    W,Hh=aspect
    ax.add_patch(Rectangle((0,0),1,1,fill=False,ec='k',lw=1.5))
    cols=plt.cm.Set2(np.linspace(0,1,len(sizes)))
    c=x.reshape(len(sizes),2)
    for i,(w,h) in enumerate(sizes):
        ax.add_patch(Rectangle((c[i,0]-w/2,c[i,1]-h/2),w,h,color=cols[i],alpha=0.75,ec='k',lw=0.8))
    ax.set_xlim(-0.05,1.05); ax.set_ylim(-0.05,1.05); ax.set_aspect(Hh/W)
    ax.set_xticks([]); ax.set_yticks([]); ax.grid(False)
    sc=lay["MSSBOA_score"] if who=="MSSBOA" else lay["SBOA_score"]
    ax.set_title(f"{who}\n{name.split(' ',1)[1]} (score={sc*100:.1f})",fontsize=9)
for j,name in enumerate(sel):
    draw(axes[0,j],name,"MSSBOA"); draw(axes[1,j],name,"SBOA")
fig.suptitle("Representative layouts optimized by MSSBOA (top) and basic SBOA (bottom)",y=1.0,fontsize=12)
fig.tight_layout(); fig.savefig(os.path.join(FIG,"fig14_layouts.png"),bbox_inches="tight"); plt.close(fig); print("fig14 done")
print("APP FIGURES DONE")
