# -*- coding: utf-8 -*-
"""Paper 2 additional references (all verified via find+adversarial-verify
workflow, 2026-07-11; evidence in refs/verified_p2.json). Combined at build
time with paper 1's REFS (shared keys: acemoglu2019/2022, frey, ilo1-3,
sts1-4, ses_urban, training1/2, alm1/2, career1)."""

REFS2 = {
 # digitalization & youth (from paper-1 verified pool)
 'basol': dict(authors='Başol, O.; Sevgi, H.; Yalçın, E.C.',
     title='The Effect of Digitalization on Youth Unemployment for EU Countries: Treat or Threat?',
     journal='Sustainability', year='2023', volume='15', pages='11080'),
 'ogbonna': dict(authors='Ogbonna, A.E.; Adediran, I.A.; Oloko, T.F.; Isah, K.O.',
     title='Information and Communication Technology (ICT) and youth unemployment in Africa',
     journal='Qual. Quant.', year='2023', volume='57', pages='5055–5077'),
 'azu': dict(authors='Azu, N.P.; Jelivov, G.; Aras, O.N.; Işık, A.',
     title='Influence of digital economy on youth unemployment in West Africa',
     journal='Transnatl. Corp. Rev.', year='2021', volume='13', pages='32–42'),

 # digital leadership
 'dl1': dict(authors='Lin, Q.',
     title='Digital leadership: A systematic literature review and future research agenda',
     journal='Eur. J. Innov. Manag.', year='2025', volume='28', pages='2469–2488'),
 'dl2': dict(authors='AlNuaimi, B.K.; Singh, S.K.; Ren, S.; Budhwar, P.; Vorobyev, D.',
     title='Mastering digital transformation: The nexus between leadership, agility, and digital strategy',
     journal='J. Bus. Res.', year='2022', volume='145', pages='636–648'),
 'dl3': dict(authors='Philip, J.; Gilli, K.; Knappstein, M.',
     title='Identifying key leadership competencies for digital transformation: Evidence from a cross-sectoral Delphi study of global managers',
     journal='Leadersh. Organ. Dev. J.', year='2023', volume='44', pages='392–406'),
 'dl4': dict(authors='Qiao, G.; Li, Y.; Hong, A.',
     title='The Strategic Role of Digital Transformation: Leveraging Digital Leadership to Enhance Employee Performance and Organizational Commitment in the Digital Era',
     journal='Systems', year='2024', volume='12', pages='457'),

 # upper echelons & executive decision making
 'upper1': dict(authors='Hambrick, D.C.; Mason, P.A.',
     title='Upper Echelons: The Organization as a Reflection of Its Top Managers',
     journal='Acad. Manag. Rev.', year='1984', volume='9', pages='193–206'),
 'upper2': dict(authors='Hambrick, D.C.',
     title='Upper Echelons Theory: An Update',
     journal='Acad. Manag. Rev.', year='2007', volume='32', pages='334–343'),
 'ceo_digital': dict(authors='Schulz, C.; Bendig, D.; Kriebel, J.; Haubner, K.; Fainshmidt, S.',
     title='CEO Human Capital and Digital Product Innovation: A Dynamic Managerial Capabilities Perspective',
     journal='Inf. Syst. Res.', year='2026', volume='37', pages='863–885'),

 # data-driven decision making / AI decision making
 'ddm1': dict(authors='Brynjolfsson, E.; McElheran, K.',
     title='The Rapid Adoption of Data-Driven Decision-Making',
     journal='Am. Econ. Rev.', year='2016', volume='106', pages='133–139'),
 'ddm2': dict(authors='Tursunbayeva, A.; Chalutz-Ben Gal, H.',
     title='Adoption of artificial intelligence: A TOP framework-based checklist for digital leaders',
     journal='Bus. Horiz.', year='2024', volume='67', pages='357–368'),
 'bda1': dict(authors='Chatterjee, S.; Chaudhuri, R.; Gupta, S.; Sivarajah, U.; Bag, S.',
     title='Assessing the impact of big data analytics on decision-making processes, forecasting, and performance of a firm',
     journal='Technol. Forecast. Soc. Change', year='2023', volume='196', pages='122824'),
 'aidm1': dict(authors='Steyvers, M.; Kumar, A.',
     title='Three Challenges for AI-Assisted Decision-Making',
     journal='Perspect. Psychol. Sci.', year='2024', volume='19', pages='722–734'),
 'systems_ai_dm': dict(authors='Song, Y.; Qiu, X.; Liu, J.',
     title='The Impact of Artificial Intelligence Adoption on Organizational Decision-Making: An Empirical Study Based on the Technology Acceptance Model in Business Management',
     journal='Systems', year='2025', volume='13', pages='683'),
 'sts_ai': dict(authors='Herrmann, T.; Pfeiffer, S.',
     title='Keeping the organization in the loop: A socio-technical extension of human-centered artificial intelligence',
     journal='AI Soc.', year='2023', volume='38', pages='1523–1542'),

 # generative AI and work
 'genai1': dict(authors='Eloundou, T.; Manning, S.; Mishkin, P.; Rock, D.',
     title='GPTs are GPTs: Labor market impact potential of LLMs',
     journal='Science', year='2024', volume='384', pages='1306–1308'),
 'genai2': dict(authors='Noy, S.; Zhang, W.',
     title='Experimental evidence on the productivity effects of generative artificial intelligence',
     journal='Science', year='2023', volume='381', pages='187–192'),
 'genai3': dict(authors='Brynjolfsson, E.; Li, D.; Raymond, L.',
     title='Generative AI at Work',
     journal='Q. J. Econ.', year='2025', volume='140', pages='889–942'),

 # EU digitalization and youth labor markets
 'eu1': dict(authors='Gomes, A.; Dias, J.G.',
     title='Digital Divide in the European Union: A Typology of EU Citizens',
     journal='Soc. Indic. Res.', year='2025', volume='176', pages='149–172'),
 'eu2': dict(authors='Sofrankova, B.; Sira, E.; Horvathova, J.; Mokrisova, M.',
     title='Digital Skills and Digital Transformation Performance in the EU-27: A DESI-Based Nonparametric and Panel Data Study',
     journal='Economies', year='2025', volume='13', pages='315'),
 'eu3': dict(authors='Drago, C.; Costantiello, A.; Savorgnan, M.; Leogrande, A.',
     title='Macroeconomic and Labor Market Drivers of AI Adoption in Europe: A Machine Learning and Panel Data Approach',
     journal='Economies', year='2025', volume='13', pages='226'),
 'stw': dict(authors='Marczuk, A.',
     title='Literature review of comparative school-to-work research: How institutional settings shape individual labour market outcomes',
     journal='J. Labour Mark. Res.', year='2024', volume='58', pages='19'),
 'neet_panel': dict(authors='Pennoni, F.; Bal-Domańska, B.',
     title='NEETs and Youth Unemployment: A Longitudinal Comparison Across European Countries',
     journal='Soc. Indic. Res.', year='2022', volume='162', pages='739–761'),
 'neet_cee': dict(authors='Karma, E.',
     title='NEET Youth in Central and Eastern European Countries: A Panel Model Approach',
     journal='J. Youth Stud.', year='2025', volume='28', pages='1458–1475'),
 'yg': dict(authors='O’Higgins, N.; Brockie, K.',
     title='The Youth Guarantee, Vulnerability, and Social Exclusion Among NEETs in Southern Europe',
     journal='Polit. Gov.', year='2024', volume='12', pages='7469'),
 'methods_app': dict(authors='Ionascu, C.M.',
     title='Artificial Intelligence Adoption in the European Union: A Data-Driven Cluster Analysis (2021–2024)',
     journal='Economies', year='2025', volume='13', pages='145'),

 # complex adaptive systems / digital organizations
 'stsd1': dict(authors='Benbya, H.; Nan, N.; Tanriverdi, H.; Yoo, Y.',
     title='Complexity and Information Systems Research in the Emerging Digital World',
     journal='MIS Q.', year='2020', volume='44', pages='1–17'),
 'stsd2': dict(authors='Browder, R.E.; Dwyer, S.M.; Koch, H.',
     title='Upgrading adaptation: How digital transformation promotes organizational resilience',
     journal='Strateg. Entrep. J.', year='2024', volume='18', pages='128–164'),

 # methods classics
 'hair': dict(authors='Hair, J.F.; Black, W.C.; Babin, B.J.; Anderson, R.E.', raw=True,
     title='Multivariate Data Analysis', journal='', year='2019',
     full='Hair, J.F.; Black, W.C.; Babin, B.J.; Anderson, R.E. Multivariate Data Analysis, 8th ed.; Cengage Learning EMEA: Andover, UK, 2019.'),
 'kaiser': dict(authors='Kaiser, H.F.',
     title='An index of factorial simplicity',
     journal='Psychometrika', year='1974', volume='39', pages='31–36'),
 'ward': dict(authors='Ward, J.H., Jr.',
     title='Hierarchical Grouping to Optimize an Objective Function',
     journal='J. Am. Stat. Assoc.', year='1963', volume='58', pages='236–244'),
 'jain': dict(authors='Jain, A.K.',
     title='Data clustering: 50 years beyond K-means',
     journal='Pattern Recognit. Lett.', year='2010', volume='31', pages='651–666'),
 'rousseeuw': dict(authors='Rousseeuw, P.J.',
     title='Silhouettes: A graphical aid to the interpretation and validation of cluster analysis',
     journal='J. Comput. Appl. Math.', year='1987', volume='20', pages='53–65'),

 # Eurostat datasets
 'ds_ict': dict(authors='Eurostat.', raw=True, title='', journal='', year='2025',
     full='Eurostat. ICT Usage and E-Commerce in Enterprises (isoc_e); Eurostat: Luxembourg, 2025. Available online: https://ec.europa.eu/eurostat (accessed on 11 July 2026).'),
 'ds_yth': dict(authors='Eurostat.', raw=True, title='', journal='', year='2025',
     full='Eurostat. Youth Employment (yth_empl); Eurostat: Luxembourg, 2025. Available online: https://ec.europa.eu/eurostat (accessed on 11 July 2026).'),
 'ds_neet': dict(authors='Eurostat.', raw=True, title='', journal='', year='2025',
     full='Eurostat. Young People Neither in Employment nor in Education and Training (edat_lfse_20); Eurostat: Luxembourg, 2025. Available online: https://ec.europa.eu/eurostat (accessed on 11 July 2026).'),
}
