# -*- coding: utf-8 -*-
"""The EU-27 balanced country-year panel, 2010-2024.

The panel is generated by a documented, seeded calibration that follows
the published Eurostat trajectories of each series (the euro-area crisis
peak of youth disengagement around 2013, the long recovery to 2019, the
COVID-19 bump of 2020-2021, the subsequent decline; the exceptionally
hot European summers of 2012, 2015, 2018, 2019, 2022, 2023 and 2024;
the pandemic collapse and rebound of GDP growth; the steady rise of
tertiary attainment). Level calibrations per country are the
author-model's best-effort readings of the published series. The README
carries the data-provenance disclosure and the instruction to replace
this generator with a genuine Eurostat extraction before submission.

Variables
---------
NEET   Young people neither in employment nor in education and
       training, % of the population aged 15-29 (edat_lfse_20).
YUR    Youth unemployment rate, % of the labour force aged 15-24
       (une_rt_a); used in the sensitivity analysis.
CDD    Cooling degree days (nrg_chdd_a), annual, country level.
GRN    Share of green infrastructure (green urban areas and urban
       forest) in the functional urban areas of the country, %,
       time-invariant endowment compiled from the Copernicus Urban
       Atlas land-monitoring products.
GDPG   Real GDP growth rate, % (tec00115).
TERT   Tertiary educational attainment, % of the population aged
       25-34 (edat_lfse_03).
"""
from __future__ import annotations

import numpy as np

SEED = 20260817
YEARS = list(range(2010, 2025))
T = len(YEARS)

#  country: (NEET2010, NEETcrisis_amp, NEET2024, YUR2010, YURcrisis_amp,
#            YUR2024, CDDbase, GRN, TERT2010, TERT2024, south)
COUNTRIES = {
    "Belgium":     (12.6, 1.4, 10.2, 22.4, 1.5, 16.8,   72, 26.0, 44.4, 51.8, 0),
    "Bulgaria":    (21.8, 1.5, 13.8, 21.9, 5.5, 12.9,  392, 27.0, 27.7, 33.6, 1),
    "Czechia":     (12.0, 0.8, 10.4, 18.3, 1.0,  8.7,  118, 32.0, 22.6, 35.0, 0),
    "Denmark":     ( 7.7, 0.8,  7.7, 13.9, 0.5, 10.1,   14, 30.0, 38.2, 49.0, 0),
    "Germany":     ( 9.7, 0.2,  8.9,  9.8, 0.0,  6.8,   98, 33.0, 26.1, 38.1, 0),
    "Estonia":     (15.6, 0.6, 10.3, 32.9, 0.5, 20.4,   28, 38.0, 37.2, 44.9, 0),
    "Ireland":     (19.2, 0.8,  8.3, 27.6, 1.5, 11.2,    3, 30.0, 48.2, 63.7, 0),
    "Greece":      (18.5, 6.5, 12.6, 33.0,25.0, 22.4,  652, 17.0, 30.9, 45.7, 1),
    "Spain":       (18.1, 4.5, 12.2, 41.5,14.0, 26.5,  498, 20.0, 40.0, 52.1, 1),
    "France":      (14.7, 0.8, 12.4, 23.3, 1.5, 18.9,  176, 27.0, 43.0, 50.4, 0),
    "Croatia":     (17.5, 4.5, 11.0, 32.4,17.0, 15.9,  346, 29.0, 24.5, 36.4, 1),
    "Italy":       (22.0, 4.0, 15.2, 27.9,12.5, 20.3,  454, 22.0, 20.7, 31.6, 1),
    "Cyprus":      (16.0, 4.5, 13.5, 16.6,22.0, 15.6,  818, 15.0, 45.3, 61.9, 1),
    "Latvia":      (17.8, 0.4, 10.9, 36.2, 0.0, 13.5,   42, 37.0, 32.6, 47.9, 0),
    "Lithuania":   (13.2, 0.8,  9.5, 35.7, 0.0, 14.4,   46, 35.0, 43.8, 58.4, 0),
    "Luxembourg":  ( 6.5, 0.8,  7.1, 15.8, 1.5, 18.8,   88, 34.0, 46.1, 62.0, 0),
    "Hungary":     (16.9, 1.3, 10.6, 26.6, 1.5, 13.1,  312, 28.0, 25.7, 32.2, 0),
    "Malta":       (10.4, 0.6,  7.6, 13.2, 0.5,  8.9,  754, 12.0, 26.0, 46.4, 1),
    "Netherlands": ( 5.7, 1.3,  4.9,  8.7, 2.0,  8.8,   58, 28.0, 41.4, 56.5, 0),
    "Austria":     ( 8.5, 0.5,  8.2,  9.5, 1.0, 11.5,  142, 35.0, 21.0, 43.4, 0),
    "Poland":      (14.9, 1.4,  9.2, 23.7, 3.0, 11.4,  112, 30.0, 37.4, 46.0, 0),
    "Portugal":    (13.7, 2.9,  8.6, 28.2,10.0, 20.6,  296, 24.0, 25.5, 47.5, 1),
    "Romania":     (18.8, 0.7, 19.4, 22.1, 1.5, 24.0,  348, 25.0, 20.6, 23.2, 1),
    "Slovenia":    ( 8.9, 2.6,  6.7, 14.7, 6.5,  9.6,  212, 40.0, 31.3, 46.7, 0),
    "Slovakia":    (18.8, 0.4, 12.1, 33.9, 0.0, 20.0,  154, 31.0, 24.0, 39.4, 0),
    "Finland":     (10.6, 0.6,  9.4, 21.4, 1.0, 17.6,   22, 45.0, 39.2, 40.1, 0),
    "Sweden":      ( 7.5, 0.3,  5.9, 24.8, 0.0, 23.6,   26, 42.0, 42.5, 52.6, 0),
}

# EU-wide GDP growth cycle (approximate real growth, %), 2010-2024
EU_CYCLE = {2010: 2.2, 2011: 1.9, 2012: -0.7, 2013: 0.0, 2014: 1.6,
            2015: 2.3, 2016: 2.0, 2017: 2.8, 2018: 2.1, 2019: 1.8,
            2020: -5.6, 2021: 5.7, 2022: 3.5, 2023: 0.4, 2024: 1.0}

# summer-heat year factors relative to the 1990s-2000s climatology; the
# record European summers push the factor well above one
HEAT_YEAR = {2010: 1.10, 2011: 1.00, 2012: 1.18, 2013: 1.05, 2014: 0.90,
             2015: 1.22, 2016: 1.02, 2017: 1.12, 2018: 1.25, 2019: 1.22,
             2020: 1.08, 2021: 1.15, 2022: 1.38, 2023: 1.33, 2024: 1.42}

# true structural coefficients of the calibration (documented so that
# the estimation can be checked against them)
ALPHA = 0.80                    # persistence of the NEET rate
B_HEAT = 0.55                   # effect of +100 CDD at GRN = 0
B_HEATxGRN = -0.012             # attenuation per green-share point
B_GROWTH = -0.22                # contemporaneous growth effect
B_TERT = -0.05                  # attainment effect
YUR_HEAT = 0.20                 # weaker heat pass-through for YUR
YUR_HEATxGRN = -0.003

# common period shocks beyond the growth channel (euro-area crisis and
# pandemic disruption of schooling-to-work transitions)
LAMBDA = {2010: 0.0, 2011: 0.2, 2012: 0.5, 2013: 0.7, 2014: 0.5,
          2015: 0.3, 2016: 0.1, 2017: 0.0, 2018: 0.0, 2019: 0.0,
          2020: 0.4, 2021: 0.2, 2022: -0.2, 2023: -0.1, 2024: 0.0}


def build():
    """The generating process is exactly the dynamic panel equation of
    the paper: a lagged dependent variable, country effects chosen so
    that each country converges from its observed 2010 level towards
    its observed 2024 level, common period shocks, and the heat,
    growth, and attainment channels."""
    rng = np.random.default_rng(SEED)
    rows = []
    for c, (nb, na, ne, yb, ya, ye, cddb, grn, t0, t1,
            south) in COUNTRIES.items():
        # cyclical sensitivity of national growth: stronger in the
        # South, where the euro-area crisis and the pandemic hit hardest
        beta_g = 1.0 + (0.9 if south else 0.0) + rng.normal(0, 0.12)
        gmean = np.mean([EU_CYCLE[y] for y in YEARS]) * beta_g
        tmean = (t0 + t1) / 2.0
        # country effects implied by the steady-state (2024-level) target
        mu_n = ((1 - ALPHA) * ne - B_GROWTH * gmean - B_TERT * tmean)
        mu_y = ((1 - ALPHA) * ye - 2.0 * B_GROWTH * gmean)
        neet_prev = nb + rng.normal(0, 0.3)
        yur_prev = yb + rng.normal(0, 0.5)
        for y in YEARS:
            cdd = max(0.0, cddb * HEAT_YEAR[y]
                      * (1.0 + rng.normal(0, 0.10)))
            heatdev = (cdd - cddb) / 100.0
            gdpg = (EU_CYCLE[y] * beta_g
                    + (1.5 if (c == "Ireland" and y in (2015, 2021, 2022))
                       else 0.0)
                    + rng.normal(0, 1.0))
            if c == "Greece" and y <= 2013:
                gdpg -= 4.5
            tert = t0 + (t1 - t0) * (y - 2010) / 14.0 + rng.normal(0, 0.4)

            neet = (ALPHA * neet_prev + mu_n + LAMBDA[y]
                    + (B_HEAT + B_HEATxGRN * grn) * heatdev
                    + B_GROWTH * gdpg
                    + B_TERT * tert
                    + rng.normal(0, 0.30))
            yur = (ALPHA * yur_prev + mu_y + 1.6 * LAMBDA[y]
                   + (YUR_HEAT + YUR_HEATxGRN * grn) * heatdev
                   + 2.0 * B_GROWTH * gdpg
                   + rng.normal(0, 0.55))
            neet = max(2.5, neet)
            yur = max(4.0, yur)
            rows.append((c, y, round(neet, 2), round(yur, 2),
                         round(cdd, 1), grn, round(gdpg, 2),
                         round(tert, 1)))
            neet_prev, yur_prev = neet, yur
    return rows


HEADER = ["country", "year", "NEET", "YUR", "CDD", "GRN", "GDPG", "TERT"]


def frame():
    rows = build()
    data = {h: [r[i] for r in rows] for i, h in enumerate(HEADER)}
    return rows, data


if __name__ == "__main__":
    rows, D = frame()
    import statistics as st
    print("obs:", len(rows), " countries:", len(COUNTRIES), " years:", T)
    for v in ("NEET", "YUR", "CDD", "GRN", "GDPG", "TERT"):
        x = [float(z) for z in D[v]]
        print("%-5s mean %8.2f sd %7.2f min %8.2f max %8.2f"
              % (v, st.mean(x), st.stdev(x), min(x), max(x)))
