# -*- coding: utf-8 -*-
"""Verified references. All entries independently verified via web search
(find + adversarial verify workflow, 2026-07-11); DOIs recorded in
refs/verified.json. MDPI style: Authors. Title. J.-Abbrev Year, Vol, Pages."""

REFS = {
 'ilo1': dict(authors='International Labour Organization (ILO).', raw=True,
              title='Global Employment Trends for Youth 2024: Decent Work, Brighter Futures',
              journal='ILO: Geneva, Switzerland', year='2024',
              full='International Labour Organization (ILO). Global Employment Trends for Youth 2024: Decent Work, Brighter Futures; ILO: Geneva, Switzerland, 2024.'),
 'ilo2': dict(authors='Rahmani, H.; Groot, W.; Rahmani, A.M.',
              title='Unravelling the NEET phenomenon: A systematic literature review and meta-analysis of risk factors for youth not in education, employment, or training',
              journal='Int. J. Adolesc. Youth', year='2024', volume='29', pages='2331576'),
 'ilo3': dict(authors='Pastore, F.; Quintano, C.; Rocca, A.',
              title='Some young people have all the luck! The duration dependence of the school-to-work transition in Europe',
              journal='Labour Econ.', year='2021', volume='70', pages='101982'),
 'china_youth1': dict(authors='Ou, D.; Zhao, Z.',
              title='Higher Education Expansion in China, 1999–2003: Impact on Graduate Employability',
              journal='China World Econ.', year='2022', volume='30', pages='117–141'),
 'china_youth2': dict(authors='Xiong, B.; Yu, B.',
              title='The Impact of Internet Development on Youth’s Job Quality in the Digital Economy Era: Transmission Mechanism and Empirical Test',
              journal='Soc. Indic. Res.', year='2024', volume='175', pages='269–294'),
 'mismatch1': dict(authors='Jones, M.K.; Kaya, E.; Nan, J.',
              title='Overeducation, earnings and job satisfaction among graduates in China',
              journal='China Econ. Rev.', year='2025', volume='93', pages='102448'),
 'mismatch2': dict(authors='Jiang, S.; Guo, Y.',
              title='Reasons for college major-job mismatch and labor market outcomes: Evidence from China',
              journal='China Econ. Rev.', year='2022', volume='74', pages='101822'),
 'acemoglu2019': dict(authors='Acemoglu, D.; Restrepo, P.',
              title='Automation and New Tasks: How Technology Displaces and Reinstates Labor',
              journal='J. Econ. Perspect.', year='2019', volume='33', pages='3–30'),
 'acemoglu2022': dict(authors='Acemoglu, D.; Restrepo, P.',
              title='Tasks, Automation, and the Rise in U.S. Wage Inequality',
              journal='Econometrica', year='2022', volume='90', pages='1973–2016'),
 'robots_us': dict(authors='Acemoglu, D.; Restrepo, P.',
              title='Robots and Jobs: Evidence from US Labor Markets',
              journal='J. Polit. Econ.', year='2020', volume='128', pages='2188–2244'),
 'robots_age': dict(authors='Deng, L.; Müller, S.; Plümpe, V.; Stegmaier, J.',
              title='Robots, occupations, and worker age: A production-unit analysis of employment',
              journal='Eur. Econ. Rev.', year='2024', volume='170', pages='104881'),
 'robots_japan': dict(authors='Adachi, D.; Kawaguchi, D.; Saito, Y.U.',
              title='Robots and Employment: Evidence from Japan, 1978–2017',
              journal='J. Labor Econ.', year='2024', volume='42', pages='591–634'),
 'robots_china_firm': dict(authors='Wang, T.; Zhang, Y.; Liu, C.',
              title='Robot adoption and employment adjustment: Firm-level evidence from China',
              journal='China Econ. Rev.', year='2024', volume='84', pages='102137'),
 'robots_china2': dict(authors='Zhu, G.; Nie, A.',
              title='How industrial robots affect employment: firm-level evidence from China',
              journal='J. Asia Pac. Econ.', year='2026', volume='31', pages='31–61'),
 'frey': dict(authors='Frey, C.B.; Osborne, M.A.',
              title='The future of employment: How susceptible are jobs to computerisation?',
              journal='Technol. Forecast. Soc. Change', year='2017', volume='114', pages='254–280'),
 'skill_demand': dict(authors='Xie, M.; Ding, L.; Xia, Y.; Guo, J.; Pan, J.; Wang, H.',
              title='Does artificial intelligence affect the pattern of skill demand? Evidence from Chinese manufacturing firms',
              journal='Econ. Model.', year='2021', volume='96', pages='295–309'),
 'career1': dict(authors='Bankins, S.; Jooss, S.; Restubog, S.L.D.; Marrone, M.; Ocampo, A.C.; Shoss, M.',
              title='Navigating career stages in the age of artificial intelligence: A systematic interdisciplinary review and agenda for future research',
              journal='J. Vocat. Behav.', year='2024', volume='153', pages='104011'),
 'career2': dict(authors='Battisti, M.; Dustmann, C.; Schönberg, U.',
              title='Technological and Organizational Change and the Careers of Workers',
              journal='J. Eur. Econ. Assoc.', year='2023', volume='21', pages='1551–1594'),
 'sts1': dict(authors='Trist, E.L.; Bamforth, K.W.',
              title='Some Social and Psychological Consequences of the Longwall Method of Coal-Getting',
              journal='Hum. Relat.', year='1951', volume='4', pages='3–38'),
 'sts2': dict(authors='Makarius, E.E.; Mukherjee, D.; Fox, J.D.; Fox, A.K.',
              title='Rising with the machines: A sociotechnical framework for bringing artificial intelligence into the organization',
              journal='J. Bus. Res.', year='2020', volume='120', pages='262–273'),
 'sts3': dict(authors='Kudina, O.; van de Poel, I.',
              title='A sociotechnical system perspective on AI',
              journal='Minds Mach.', year='2024', volume='34', pages='21'),
 'sts4': dict(authors='Iden, J.; Bygstad, B.',
              title='Sociotechnical micro-foundations for digital transformation',
              journal='Eur. J. Inf. Syst.', year='2025', volume='34', pages='367–382'),
 'ses_regional': dict(authors='Yang, Y.; Lin, G.T.R.',
              title='Local Digital Economic Growth, Enterprise Digital Transformation, and Digital Dividends: Evidence from China',
              journal='Systems', year='2025', volume='13', pages='297'),
 'ses_urban': dict(authors='Fernández-Portillo, A.; Ramos-Vecino, N.; Calzado-Barbero, M.; Robina-Ramírez, R.',
              title='Does Innovation Create Employment Indirectly through the Improvement Generated in the Company’s Economic and Financial Results?',
              journal='Systems', year='2023', volume='11', pages='381'),
 'zhejiang1': dict(authors='Zhuang, T.; Zhao, S.',
              title='Collaborative innovation relationship in Yangtze River Delta of China: Subjects collaboration and spatial correlation',
              journal='Technol. Soc.', year='2022', volume='69', pages='101974'),
 'zhejiang2': dict(authors='Cheng, H.; Jia, R.; Li, D.; Li, H.',
              title='The Rise of Robots in China',
              journal='J. Econ. Perspect.', year='2019', volume='33', pages='71–88'),
 'digital_emp1': dict(authors='Dou, B.; Guo, S.; Chang, X.; Wang, Y.',
              title='Corporate digital transformation and labor structure upgrading',
              journal='Int. Rev. Financ. Anal.', year='2023', volume='90', pages='102904'),
 'digital_emp2': dict(authors='Zhong, S.; Zhang, X.; Zhang, L.; Zhao, C.',
              title='How does digital economy influence urban common prosperity? Evidence from China’s demonstration area for common prosperity',
              journal='Int. Rev. Econ. Financ.', year='2025', volume='104', pages='104629'),
 'pilot1': dict(authors='Huang, Y.; Liu, S.; Gan, J.; Liu, B.; Wu, Y.',
              title='How does the construction of new generation of national AI innovative development pilot zones drive enterprise ESG development? Empirical evidence from China',
              journal='Energy Econ.', year='2024', volume='140', pages='108011'),
 'pilot2': dict(authors='Xu, Y.; Wei, Y.; Zeng, X.; Yu, H.; Chen, H.',
              title='Big data development and labor income share: Evidence from China’s national big data comprehensive pilot zones',
              journal='Econ. Anal. Policy', year='2024', volume='84', pages='1415–1437'),
 'oipt': dict(authors='Tushman, M.L.; Nadler, D.A.',
              title='Information processing as an integrating concept in organizational design',
              journal='Acad. Manag. Rev.', year='1978', volume='3', pages='613–624'),
 'teece': dict(authors='Teece, D.J.',
              title='Explicating dynamic capabilities: The nature and microfoundations of (sustainable) enterprise performance',
              journal='Strateg. Manag. J.', year='2007', volume='28', pages='1319–1350'),
 'training1': dict(authors='Heß, P.; Janssen, S.; Leber, U.',
              title='The effect of automation technology on workers’ training participation',
              journal='Econ. Educ. Rev.', year='2023', volume='96', pages='102438'),
 'training2': dict(authors='Konings, J.; Vanormelingen, S.',
              title='The Impact of Training on Productivity and Wages: Firm-Level Evidence',
              journal='Rev. Econ. Stat.', year='2015', volume='97', pages='485–497'),
 'alm1': dict(authors='Card, D.; Kluve, J.; Weber, A.',
              title='What Works? A Meta Analysis of Recent Active Labor Market Program Evaluations',
              journal='J. Eur. Econ. Assoc.', year='2018', volume='16', pages='894–931'),
 'alm2': dict(authors='Kluve, J.; Puerto, S.; Robalino, D.; Romero, J.M.; Rother, F.; Stöterau, J.; Weidenkaff, F.; Witte, M.',
              title='Do youth employment programs improve labor market outcomes? A quantitative review',
              journal='World Dev.', year='2019', volume='114', pages='237–253'),
 'vet1': dict(authors='Dai, L.; Martins, P.S.',
              title='Does vocational education pay off in China? Evidence from city-level education supply shocks',
              journal='Econ. Model.', year='2024', volume='140', pages='106863'),
 'esg_labor': dict(authors='Yang, X.; Wang, C.; Liu, B.',
              title='ESG performance and corporate labor investment efficiency: Evidence from China',
              journal='Int. Rev. Econ. Financ.', year='2025', volume='98', pages='103909'),
 'textmeasure1': dict(authors='Lu, R.; Peng, X.; Reve, T.',
              title='Firms’ digital transformation, competitive strategies, and innovation: Evidence from Chinese listed companies',
              journal='J. Manag. Organ.', year='2025', volume='31', pages='575–601'),
 'textmeasure2': dict(authors='Fang, L.; Li, Z.',
              title='Corporate digitalization and green innovation: Evidence from textual analysis of firm annual reports and corporate green patent data in China',
              journal='Bus. Strategy Environ.', year='2024', volume='33', pages='3936–3964'),
 'textdata': dict(authors='Gentzkow, M.; Kelly, B.; Taddy, M.',
              title='Text as Data',
              journal='J. Econ. Lit.', year='2019', volume='57', pages='535–574'),
 'bartik': dict(authors='Goldsmith-Pinkham, P.; Sorkin, I.; Swift, H.',
              title='Bartik Instruments: What, When, Why, and How',
              journal='Am. Econ. Rev.', year='2020', volume='110', pages='2586–2624'),
 'psm': dict(authors='Shipman, J.E.; Swanquist, Q.T.; Whited, R.L.',
              title='Propensity Score Matching in Accounting Research',
              journal='Account. Rev.', year='2017', volume='92', pages='213–244'),
 'prod1': dict(authors='Huang, K.; Liu, Q.; Tang, C.',
              title='Which firms benefit from robot adoption? Evidence from China',
              journal='J. Asian Econ.', year='2023', volume='86', pages='101612'),
 'sbtc1': dict(authors='Cheng, C.; Luo, J.; Zhu, C.; Zhang, S.',
              title='Artificial intelligence and the skill premium: A numerical analysis of theoretical models',
              journal='Technol. Forecast. Soc. Change', year='2024', volume='200', pages='123140'),
 'gig1': dict(authors='Wang, X.; Jiang, Y.; Yi, F.',
              title='Digital Revolution and Job Quality of Lower Class Workers: Quasi-experimental Evidence from the Broadband China Program',
              journal='China World Econ.', year='2024', volume='32', pages='146–178'),
 'im_hc': dict(authors='Li, X.; Wang, Q.; Kong, D.; Tao, Y.',
              title='Intelligent Manufacturing and Corporate Human Capital Upgrade in China',
              journal='J. Asian Econ.', year='2025', volume='97', pages='101886'),
 'broadband': dict(authors='Jin, X.; Ma, B.; Zhang, H.',
              title='Impact of fast internet access on employment: Evidence from a broadband expansion in China',
              journal='China Econ. Rev.', year='2023', volume='81', pages='102038'),
 'talent': dict(authors='Hua, Z.; Kong, S.; Yu, Y.',
              title='Talent magnets in China: Can talent attraction policies catalyze digital transformation in enterprises?',
              journal='China Econ. Rev.', year='2025', volume='90', pages='102376'),
 'mediation1': dict(authors='Baron, R.M.; Kenny, D.A.',
              title='The moderator–mediator variable distinction in social psychological research: Conceptual, strategic, and statistical considerations',
              journal='J. Pers. Soc. Psychol.', year='1986', volume='51', pages='1173–1182'),
 'mediation2': dict(authors='Imai, K.; Keele, L.; Tingley, D.',
              title='A general approach to causal mediation analysis',
              journal='Psychol. Methods', year='2010', volume='15', pages='309–334'),
 'twfe': dict(authors='de Chaisemartin, C.; D’Haultfœuille, X.',
              title='Two-Way Fixed Effects Estimators with Heterogeneous Treatment Effects',
              journal='Am. Econ. Rev.', year='2020', volume='110', pages='2964–2996'),
}
