# -*- coding: utf-8 -*-
"""Paper 3 references — APA fields (Behavioral Sciences author-date style).
All entries verified via the find+adversarial-verify workflow (evidence in
references_verified.json); DOIs/issues merged from verifier output by
merge_refs.py. 'intext' is the in-text citation head; 'raw' entries render
their 'full' string verbatim (⟦...⟧ = italics)."""

REFS3 = {
 # --- AI / NLP in psychology (SI core) ---
 'demszky2023': dict(intext='Demszky et al.', year='2023',
    authors='Demszky, D., Yang, D., Yeager, D. S., Bryan, C. J., Clapper, M., Chandhok, S., Eichstaedt, J. C., Hecht, C., Jamieson, J., Johnson, M., Jones, M., Krettek-Cobb, D., Lai, L., JonesMitchell, N., Ong, D. C., Dweck, C. S., Gross, J. J., & Pennebaker, J. W.',
    title='Using large language models in psychology',
    journal='Nature Reviews Psychology', volume='2', issue='11', pages='688–701'),
 'rathje2024': dict(intext='Rathje et al.', year='2024',
    authors='Rathje, S., Mirea, D.-M., Sucholutsky, I., Marjieh, R., Robertson, C. E., & Van Bavel, J. J.',
    title='GPT is an effective tool for multilingual psychological text analysis',
    journal='Proceedings of the National Academy of Sciences', volume='121', issue='34', pages='e2308950121'),
 'kjell2024': dict(intext='Kjell et al.', year='2024',
    authors='Kjell, O. N. E., Kjell, K., & Schwartz, H. A.',
    title='Beyond rating scales: With targeted evaluation, large language models are poised for psychological assessment',
    journal='Psychiatry Research', volume='333', pages='115667'),
 'kjell2019': dict(intext='Kjell et al.', year='2019',
    authors='Kjell, O. N. E., Kjell, K., Garcia, D., & Sikström, S.',
    title='Semantic measures: Using natural language processing to measure, differentiate, and describe psychological constructs',
    journal='Psychological Methods', volume='24', issue='1', pages='92–115'),
 'kjell2022': dict(intext='Kjell et al.', year='2022',
    authors='Kjell, O. N. E., Sikström, S., Kjell, K., & Schwartz, H. A.',
    title='Natural language analyzed with AI-based transformers predict traditional subjective well-being measures approaching the theoretical upper limits in accuracy',
    journal='Scientific Reports', volume='12', pages='3918'),
 'boyd2021': dict(intext='Boyd & Schwartz', year='2021',
    authors='Boyd, R. L., & Schwartz, H. A.',
    title='Natural language analysis and the psychology of verbal behavior: The past, present, and future states of the field',
    journal='Journal of Language and Social Psychology', volume='40', issue='1', pages='21–41'),
 'eichstaedt2018': dict(intext='Eichstaedt et al.', year='2018',
    authors='Eichstaedt, J. C., Smith, R. J., Merchant, R. M., Ungar, L. H., Crutchley, P., Preoţiuc-Pietro, D., Asch, D. A., & Schwartz, H. A.',
    title='Facebook language predicts depression in medical records',
    journal='Proceedings of the National Academy of Sciences', volume='115', issue='44', pages='11203–11208'),
 'tausczik2010': dict(intext='Tausczik & Pennebaker', year='2010',
    authors='Tausczik, Y. R., & Pennebaker, J. W.',
    title='The psychological meaning of words: LIWC and computerized text analysis methods',
    journal='Journal of Language and Social Psychology', volume='29', issue='1', pages='24–54'),
 'ziems2024': dict(intext='Ziems et al.', year='2024',
    authors='Ziems, C., Held, W., Shaikh, O., Chen, J., Zhang, Z., & Yang, D.',
    title='Can large language models transform computational social science?',
    journal='Computational Linguistics', volume='50', issue='1', pages='237–291'),
 'peters2024': dict(intext='Peters & Matz', year='2024',
    authors='Peters, H., & Matz, S. C.',
    title='Large language models can infer psychological dispositions of social media users',
    journal='PNAS Nexus', volume='3', issue='6', pages='pgae231'),
 'gilardi2023': dict(intext='Gilardi et al.', year='2023',
    authors='Gilardi, F., Alizadeh, M., & Kubli, M.',
    title='ChatGPT outperforms crowd workers for text-annotation tasks',
    journal='Proceedings of the National Academy of Sciences', volume='120', issue='30', pages='e2305016120'),
 'xu2024': dict(intext='Xu et al.', year='2024',
    authors='Xu, X., Yao, B., Dong, Y., Gabriel, S., Yu, H., Hendler, J., Ghassemi, M., Dey, A. K., & Wang, D.',
    title='Mental-LLM: Leveraging large language models for mental health prediction via online text data',
    journal='Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies', volume='8', issue='1', pages='Article 31'),
 'elyoseph2023': dict(intext='Elyoseph et al.', year='2023',
    authors='Elyoseph, Z., Hadar-Shoval, D., Asraf, K., & Lvovsky, M.',
    title='ChatGPT outperforms humans in emotional awareness evaluations',
    journal='Frontiers in Psychology', volume='14', pages='1199058'),
 'abdurahman2024': dict(intext='Abdurahman et al.', year='2024',
    authors='Abdurahman, S., Atari, M., Karimi-Malekabadi, F., Xue, M. J., Trager, J., Park, P. S., Golazizian, P., Omrani, A., & Dehghani, M.',
    title='Perils and opportunities in using large language models in psychological research',
    journal='PNAS Nexus', volume='3', issue='7', pages='pgae245'),
 'sikstrom2020': dict(intext='Sikström & Garcia', year='2020', raw=True,
    authors='Sikström, S., & Garcia, D.',
    title='Statistical semantics', journal='',
    full='Sikström, S., & Garcia, D. (Eds.). (2020). ⟦Statistical semantics: Methods and applications⟧. Springer.'),
 'insel2017': dict(intext='Insel', year='2017',
    authors='Insel, T. R.',
    title='Digital phenotyping: Technology for a new science of behavior',
    journal='JAMA', volume='318', issue='13', pages='1215–1216'),
 'mcgorry2024': dict(intext='McGorry et al.', year='2024',
    authors='McGorry, P. D., Mei, C., Dalal, N., Alvarez-Jimenez, M., Blakemore, S.-J., Browne, V., Dooley, B., Hickie, I. B., Jones, P. B., McDaid, D., Mihalopoulos, C., Wood, S. J., El Azzouzi, F. A., Fazio, J., Gow, E., Hanjabam, S., Hayes, A., Morris, A., Pang, E., ... Killackey, E.',
    title='The Lancet Psychiatry Commission on youth mental health',
    journal='The Lancet Psychiatry', volume='11', issue='9', pages='731–774'),

 # --- models / software (raw) ---
 'openai_gpt4o': dict(intext='OpenAI', year='2024', raw=True,
    authors='OpenAI', title='GPT-4o system card', journal='',
    full='OpenAI. (2024). ⟦GPT-4o system card⟧ (arXiv:2410.21276). arXiv. https://doi.org/10.48550/arXiv.2410.21276'),
 'qwen25': dict(intext='Qwen Team', year='2024', raw=True,
    authors='Qwen Team', title='Qwen2.5 technical report', journal='',
    full='Qwen Team. (2024). ⟦Qwen2.5 technical report⟧ (arXiv:2412.15115). arXiv. https://doi.org/10.48550/arXiv.2412.15115'),
 'bgem3': dict(intext='Chen et al.', year='2024', raw=True,
    authors='Chen, J., Xiao, S., Zhang, P., Luo, K., Lian, D., & Liu, Z.',
    title='M3-Embedding', journal='',
    full='Chen, J., Xiao, S., Zhang, P., Luo, K., Lian, D., & Liu, Z. (2024). M3-Embedding: Multi-linguality, multi-functionality, multi-granularity text embeddings through self-knowledge distillation. In ⟦Findings of the Association for Computational Linguistics: ACL 2024⟧ (pp. 2318–2335). Association for Computational Linguistics.'),
 'reimers2019': dict(intext='Reimers & Gurevych', year='2019', raw=True,
    authors='Reimers, N., & Gurevych, I.', title='Sentence-BERT', journal='',
    full='Reimers, N., & Gurevych, I. (2019). Sentence-BERT: Sentence embeddings using Siamese BERT-networks. In ⟦Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing and the 9th International Joint Conference on Natural Language Processing (EMNLP-IJCNLP)⟧ (pp. 3982–3992). Association for Computational Linguistics.'),
 'grootendorst2022': dict(intext='Grootendorst', year='2022', raw=True,
    authors='Grootendorst, M.', title='BERTopic', journal='',
    full='Grootendorst, M. (2022). ⟦BERTopic: Neural topic modeling with a class-based TF-IDF procedure⟧ (arXiv:2203.05794). arXiv. https://doi.org/10.48550/arXiv.2203.05794'),
 'mcinnes2018': dict(intext='McInnes et al.', year='2018', raw=True,
    authors='McInnes, L., Healy, J., & Melville, J.', title='UMAP', journal='',
    full='McInnes, L., Healy, J., & Melville, J. (2018). ⟦UMAP: Uniform manifold approximation and projection for dimension reduction⟧ (arXiv:1802.03426). arXiv. https://doi.org/10.48550/arXiv.1802.03426'),

 # --- career psychology & instruments ---
 'creed2016': dict(intext='Creed et al.', year='2016',
    authors='Creed, P. A., Hood, M., Praskova, A., & Makransky, G.',
    title='The Career Distress Scale: Using Rasch measurement theory to evaluate a brief measure of career distress',
    journal='Journal of Career Assessment', volume='24', issue='4', pages='732–746'),
 'maggiori2017': dict(intext='Maggiori et al.', year='2017',
    authors='Maggiori, C., Rossier, J., & Savickas, M. L.',
    title='Career Adapt-Abilities Scale–Short Form (CAAS-SF): Construction and validation',
    journal='Journal of Career Assessment', volume='25', issue='2', pages='312–325'),
 'savickas2012': dict(intext='Savickas & Porfeli', year='2012',
    authors='Savickas, M. L., & Porfeli, E. J.',
    title='Career Adapt-Abilities Scale: Construction, reliability, and measurement equivalence across 13 countries',
    journal='Journal of Vocational Behavior', volume='80', issue='3', pages='661–673'),
 'hou2012': dict(intext='Hou et al.', year='2012',
    authors='Hou, Z.-J., Leung, S. A., Li, X., Li, X., & Xu, H.',
    title='Career Adapt-Abilities Scale—China Form: Construction and initial validation',
    journal='Journal of Vocational Behavior', volume='80', issue='3', pages='686–691'),
 'rothwell2007': dict(intext='Rothwell & Arnold', year='2007',
    authors='Rothwell, A., & Arnold, J.',
    title='Self-perceived employability: Development and validation of a scale',
    journal='Personnel Review', volume='36', issue='1', pages='23–41'),
 'rudolph2017': dict(intext='Rudolph et al.', year='2017',
    authors='Rudolph, C. W., Lavigne, K. N., & Zacher, H.',
    title='Career adaptability: A meta-analysis of relationships with measures of adaptivity, adapting responses, and adaptation results',
    journal='Journal of Vocational Behavior', volume='98', pages='17–34'),
 'savickas2013': dict(intext='Savickas', year='2013', raw=True,
    authors='Savickas, M. L.', title='Career construction theory and practice', journal='',
    full='Savickas, M. L. (2013). Career construction theory and practice. In S. D. Brown & R. W. Lent (Eds.), ⟦Career development and counseling: Putting theory and research to work⟧ (2nd ed., pp. 147–183). John Wiley & Sons.'),
 'duffy2016': dict(intext='Duffy et al.', year='2016',
    authors='Duffy, R. D., Blustein, D. L., Diemer, M. A., & Autin, K. L.',
    title='The psychology of working theory',
    journal='Journal of Counseling Psychology', volume='63', issue='2', pages='127–148'),
 'spitzer2006': dict(intext='Spitzer et al.', year='2006',
    authors='Spitzer, R. L., Kroenke, K., Williams, J. B. W., & Löwe, B.',
    title='A brief measure for assessing generalized anxiety disorder: The GAD-7',
    journal='Archives of Internal Medicine', volume='166', issue='10', pages='1092–1097'),
 'kroenke2009': dict(intext='Kroenke et al.', year='2009',
    authors='Kroenke, K., Strine, T. W., Spitzer, R. L., Williams, J. B. W., Berry, J. T., & Mokdad, A. H.',
    title='The PHQ-8 as a measure of current depression in the general population',
    journal='Journal of Affective Disorders', volume='114', issue='1–3', pages='163–173'),
 'diener1985': dict(intext='Diener et al.', year='1985',
    authors='Diener, E., Emmons, R. A., Larsen, R. J., & Griffin, S.',
    title='The Satisfaction With Life Scale',
    journal='Journal of Personality Assessment', volume='49', issue='1', pages='71–75'),

 # --- job search / unemployment / NEET ---
 'wanberg2020': dict(intext='Wanberg et al.', year='2020',
    authors='Wanberg, C. R., Ali, A. A., & Csillag, B.',
    title='Job seeking: The process and experience of looking for a job',
    journal='Annual Review of Organizational Psychology and Organizational Behavior', volume='7', pages='315–337'),
 'vanhooft2021': dict(intext='van Hooft et al.', year='2021',
    authors='van Hooft, E. A. J., Kammeyer-Mueller, J. D., Wanberg, C. R., Kanfer, R., & Basbug, G.',
    title='Job search and employment success: A quantitative review and future research agenda',
    journal='Journal of Applied Psychology', volume='106', issue='5', pages='674–713'),
 'paul2009': dict(intext='Paul & Moser', year='2009',
    authors='Paul, K. I., & Moser, K.',
    title='Unemployment impairs mental health: Meta-analyses',
    journal='Journal of Vocational Behavior', volume='74', issue='3', pages='264–282'),
 'gariepy2022': dict(intext='Gariépy et al.', year='2022',
    authors='Gariépy, G., Danna, S. M., Hawke, L., Henderson, J., & Iyer, S. N.',
    title='The mental health of young people who are not in education, employment, or training: A systematic review and meta-analysis',
    journal='Social Psychiatry and Psychiatric Epidemiology', volume='57', issue='6', pages='1107–1121'),
 'rahmani2024': dict(intext='Rahmani et al.', year='2024',
    authors='Rahmani, H., Groot, W., & Rahmani, A. M.',
    title='Unravelling the NEET phenomenon: A systematic literature review and meta-analysis of risk factors for youth not in education, employment, or training',
    journal='International Journal of Adolescence and Youth', volume='29', issue='1', pages='2331576'),
 'ilo2024': dict(intext='International Labour Organization', year='2024', raw=True,
    authors='International Labour Organization', title='Global employment trends for youth 2024', journal='',
    full='International Labour Organization. (2024). ⟦Global employment trends for youth 2024: Decent work, brighter futures⟧. International Labour Office. https://doi.org/10.54394/QSMU1809'),

 # --- China youth employment context ---
 'ou2022': dict(intext='Ou & Zhao', year='2022',
    authors='Ou, D., & Zhao, Z.',
    title='Higher education expansion in China, 1999–2003: Impact on graduate employability',
    journal='China & World Economy', volume='30', issue='2', pages='117–141'),
 'jones2025': dict(intext='Jones et al.', year='2025',
    authors='Jones, M. K., Kaya, E., & Nan, J.',
    title='Overeducation, earnings and job satisfaction among graduates in China',
    journal='China Economic Review', volume='93', pages='102448'),
 'xiong2024': dict(intext='Xiong & Yu', year='2024',
    authors='Xiong, B., & Yu, B.',
    title='The impact of Internet development on youth’s job quality in the digital economy era: Transmission mechanism and empirical test',
    journal='Social Indicators Research', volume='175', pages='269–294'),

 # --- AI and the future of (young) work ---
 'bankins2024': dict(intext='Bankins et al.', year='2024',
    authors='Bankins, S., Jooss, S., Restubog, S. L. D., Marrone, M., Ocampo, A. C., & Shoss, M.',
    title='Navigating career stages in the age of artificial intelligence: A systematic interdisciplinary review and agenda for future research',
    journal='Journal of Vocational Behavior', volume='153', pages='104011'),
 'eloundou2024': dict(intext='Eloundou et al.', year='2024',
    authors='Eloundou, T., Manning, S., Mishkin, P., & Rock, D.',
    title='GPTs are GPTs: Labor market impact potential of LLMs',
    journal='Science', volume='384', issue='6702', pages='1306–1308'),
 'noy2023': dict(intext='Noy & Zhang', year='2023',
    authors='Noy, S., & Zhang, W.',
    title='Experimental evidence on the productivity effects of generative artificial intelligence',
    journal='Science', volume='381', issue='6654', pages='187–192'),
 'brynjolfsson2025': dict(intext='Brynjolfsson et al.', year='2025',
    authors='Brynjolfsson, E., Li, D., & Raymond, L.',
    title='Generative AI at work',
    journal='The Quarterly Journal of Economics', volume='140', issue='2', pages='889–942'),

 # --- statistics / methods ---
 'koo2016': dict(intext='Koo & Li', year='2016',
    authors='Koo, T. K., & Li, M. Y.',
    title='A guideline of selecting and reporting intraclass correlation coefficients for reliability research',
    journal='Journal of Chiropractic Medicine', volume='15', issue='2', pages='155–163'),
 'shrout1979': dict(intext='Shrout & Fleiss', year='1979',
    authors='Shrout, P. E., & Fleiss, J. L.',
    title='Intraclass correlations: Uses in assessing rater reliability',
    journal='Psychological Bulletin', volume='86', issue='2', pages='420–428'),
 'cohen1960': dict(intext='Cohen', year='1960',
    authors='Cohen, J.',
    title='A coefficient of agreement for nominal scales',
    journal='Educational and Psychological Measurement', volume='20', issue='1', pages='37–46'),
 'bh1995': dict(intext='Benjamini & Hochberg', year='1995',
    authors='Benjamini, Y., & Hochberg, Y.',
    title='Controlling the false discovery rate: A practical and powerful approach to multiple testing',
    journal='Journal of the Royal Statistical Society: Series B (Methodological)', volume='57', issue='1', pages='289–300'),
 'delong1988': dict(intext='DeLong et al.', year='1988',
    authors='DeLong, E. R., DeLong, D. M., & Clarke-Pearson, D. L.',
    title='Comparing the areas under two or more correlated receiver operating characteristic curves: A nonparametric approach',
    journal='Biometrics', volume='44', issue='3', pages='837–845'),
 'rousseeuw1987': dict(intext='Rousseeuw', year='1987',
    authors='Rousseeuw, P. J.',
    title='Silhouettes: A graphical aid to the interpretation and validation of cluster analysis',
    journal='Journal of Computational and Applied Mathematics', volume='20', pages='53–65'),
 'hayes2020': dict(intext='Hayes & Coutts', year='2020',
    authors='Hayes, A. F., & Coutts, J. J.',
    title="Use omega rather than Cronbach's alpha for estimating reliability. But…",
    journal='Communication Methods and Measures', volume='14', issue='1', pages='1–24'),
}

# --- verified finder additions (see references_verified.json) ---
REFS3['involution'] = dict(intext='W. Zhang et al.', sort='zhang w', year='2025',
    authors='Zhang, W., Wang, Y., Liu, X., Guo, C., Lin, Z., Zhou, M., & Mu, Y.',
    title='The psychology of involution: Taxonomy, sociocultural predictors, and psychological outcomes',
    journal='Journal of Happiness Studies', volume='26', issue='7', pages='Article 127',
    doi='10.1007/s10902-025-00954-9')
REFS3['lieflat'] = dict(intext='L. Zhang et al.', sort='zhang l', year='2025',
    authors='Zhang, L., Hui, B. P. H., Kong, F., Lu, H., & Chen, S. X.',
    title='Why people “lie flat”? An integrative framework of social-psychological pathways in China',
    journal='Personality and Social Psychology Review', volume='29', issue='4', pages='371–382',
    doi='10.1177/10888683251358516')
REFS3['peng2024'] = dict(intext='Peng et al.', year='2024',
    authors='Peng, Y., Lv, S. B., Low, S. R., & Bono, S. A.',
    title='The impact of employment stress on college students: Psychological well-being during COVID-19 pandemic in China',
    journal='Current Psychology', volume='43', issue='20', pages='18647–18658',
    doi='10.1007/s12144-023-04785-w')
REFS3['ai_career_rev'] = dict(intext='Pandya & Wang', year='2024',
    authors='Pandya, S. S., & Wang, J.',
    title='Artificial intelligence in career development: A scoping review',
    journal='Human Resource Development International', volume='27', issue='3', pages='324–344',
    doi='10.1080/13678868.2024.2336881')
REFS3['ai_career_bs'] = dict(intext='Xiao & Zheng', year='2025',
    authors='Xiao, Y., & Zheng, L.',
    title='Can ChatGPT boost students’ employment confidence? A pioneering booster for career readiness',
    journal='Behavioral Sciences', volume='15', issue='3', pages='362',
    doi='10.3390/bs15030362')
