# -*- coding: utf-8 -*-
"""A simulated ecological momentary assessment (EMA) corpus of emotion
regulation in daily life.

The corpus is generated by an explicit, seeded psychological process
model rather than sampled from an existing archive, so that the
episode-level regulatory ground truth needed to evaluate the
auditability of an assessment model is available. Every structural
parameter is anchored to published values:

*   affective inertia (the lag-one autocorrelation of momentary
    negative affect) is centred on 0.35, the value reported for
    community samples in experience-sampling work;
*   within-person variability of momentary negative affect is centred
    on 0.75 scale points on a seven-point scale;
*   prompt compliance is 85 per cent, the level typically achieved in
    signal-contingent designs, which yields variable-length sequences;
*   trait questionnaire proxies reproduce the published means and
    standard deviations of the Emotion Regulation Questionnaire
    (reappraisal M = 4.9, SD = 0.9; suppression M = 3.4, SD = 1.1) and
    of the Difficulties in Emotion Regulation Scale (M = 80, SD = 20).

Regulatory behaviour follows the process model of emotion regulation:
at every prompt the person deploys one of five strategy families —
situation selection, situation modification, attentional deployment,
cognitive change, and response modulation. Which family is deployed
depends on the person's habitual tendency, on the perceived
controllability of the episode, and on an individual regulatory
flexibility parameter that governs how strongly deployment tracks
context; how well it works depends on the fit between the family and
the controllability of the situation.
"""
from __future__ import annotations

import numpy as np

SEED = 20260819

N_PART = 420                 # participants
N_DAYS = 14                  # days of the sampling burst
N_PROMPT = 6                 # signal-contingent prompts per day
T_MAX = N_DAYS * N_PROMPT    # 84 scheduled prompts
COMPLIANCE = 0.85            # probability that a prompt is answered

FAMILIES = ["Situation selection", "Situation modification",
            "Attentional deployment", "Cognitive change",
            "Response modulation"]
FAM_SHORT = ["SS", "SM", "AD", "CC", "RM"]
K_FAM = len(FAMILIES)

# Fit between a strategy family and the perceived controllability of the
# episode. Entries give the controllability level at which the family is
# most effective and the sharpness of that tuning. Situation selection
# and situation modification act on the situation itself and therefore
# require controllability; attentional deployment and cognitive change
# act on the person's engagement with the situation and are the
# strategies of choice when the situation cannot be changed; response
# modulation is comparatively insensitive to controllability but is the
# least effective family overall.
FIT_CENTRE = np.array([0.80, 0.85, 0.25, 0.30, 0.50])
FIT_SHARP = np.array([2.6, 2.8, 2.4, 2.2, 0.8])
FAM_EFFICACY = np.array([0.55, 0.65, 0.50, 0.70, 0.30])

FEATURES = [
    "negative affect", "positive affect", "arousal",
    "stressor intensity", "controllability appraisal",
    "social presence", "at home", "time of day (sin)",
    "time of day (cos)", "day in protocol", "regulatory effort",
    "perceived regulation success", "response latency",
    "item: changed the situation", "item: looked away or distracted",
    "item: thought about it differently", "item: kept it inside",
]
F_DIM = len(FEATURES)

# Cross-loadings of the four momentary regulation items on the five
# families. The items are deliberately ambiguous indicators, as EMA
# self-reports of regulation are in practice.
ITEM_LOAD = np.array([
    #  SS    SM    AD    CC    RM
    [0.55, 0.85, 0.10, 0.10, 0.05],   # changed the situation
    [0.45, 0.10, 0.85, 0.25, 0.15],   # looked away or distracted
    [0.05, 0.15, 0.30, 0.85, 0.10],   # thought about it differently
    [0.15, 0.05, 0.20, 0.10, 0.85],   # kept it inside
])


def _fit(ctrl):
    """Strategy-situation fit for each family at a controllability level."""
    return np.exp(-FIT_SHARP * (ctrl - FIT_CENTRE) ** 2)


def generate(seed=SEED):
    rng = np.random.default_rng(seed)
    n = N_PART

    # ---- person-level latent structure --------------------------------
    # Correlated habitual tendencies: engagement-oriented families load
    # together, response modulation is largely separate.
    load = np.array([
        [0.75, 0.10], [0.80, 0.05], [0.35, 0.55],
        [0.70, 0.15], [0.10, 0.80],
    ])
    common = rng.normal(size=(n, 2))
    trait = common @ load.T + 0.55 * rng.normal(size=(n, K_FAM))
    flex = 0.5 + 0.5 * (0.6 * common[:, 0] + 0.8 * rng.normal(size=n))
    flex = np.clip(flex, 0.0, 2.0)

    mu_na = 2.9 + 0.55 * rng.normal(size=n) + 0.25 * (-common[:, 0])
    inertia = np.clip(0.46 + 0.10 * rng.normal(size=n), 0.05, 0.80)
    sd_na = np.clip(0.75 + 0.18 * rng.normal(size=n), 0.25, 1.4)

    X = np.zeros((n, T_MAX, F_DIM))
    mask = np.zeros((n, T_MAX), dtype=bool)
    used = np.full((n, T_MAX), -1, dtype=int)          # family deployed
    fitv = np.zeros((n, T_MAX))                        # realised fit
    succ = np.zeros((n, T_MAX))                        # regulation success

    for i in range(n):
        na = mu_na[i]
        for t in range(T_MAX):
            day = t // N_PROMPT
            slot = t % N_PROMPT
            answered = rng.random() < COMPLIANCE
            # ---- episode context
            stress = np.clip(rng.beta(2.0, 3.2) + 0.10 * (slot >= 4), 0, 1)
            ctrl = np.clip(rng.beta(2.2, 2.2), 0.02, 0.98)
            soc = float(rng.random() < 0.55)
            home = float(rng.random() < (0.65 if slot in (0, 5) else 0.35))

            # ---- momentary negative affect: AR(1) with inertia
            na = (mu_na[i] + inertia[i] * (na - mu_na[i])
                  + 1.35 * stress + sd_na[i] * rng.normal())
            na = float(np.clip(na, 1.0, 7.0))
            pa = float(np.clip(7.2 - 0.62 * na + 0.55 * rng.normal(),
                               1.0, 7.0))
            arousal = float(np.clip(2.4 + 0.45 * na + 0.9 * stress
                                    + 0.5 * rng.normal(), 1.0, 7.0))

            # ---- strategy deployment
            f = _fit(ctrl)
            logits = 1.15 * trait[i] + flex[i] * 1.8 * (f - f.mean())
            logits = logits + 0.45 * stress * np.array(
                [0.2, 0.5, 0.3, 0.4, 0.6])
            logits = logits + soc * np.array(
                [0.0, -0.16, 0.0, 0.0, 0.28])
            logits = logits + np.array([0.06, 0.10, 0.04, 0.10, -0.62])
            p = np.exp(logits - logits.max())
            p = p / p.sum()
            k = int(rng.choice(K_FAM, p=p))

            effort = float(np.clip(2.5 + 0.55 * stress * 4.0
                                   + 0.5 * rng.normal(), 1.0, 7.0))
            s = float(np.clip(FAM_EFFICACY[k] * f[k] * (0.6 + 0.5 * ctrl)
                              + 0.16 * rng.normal(), 0.0, 1.0))
            na = float(np.clip(na - 2.1 * s, 1.0, 7.0))
            perceived = float(np.clip(1.0 + 6.0 * s + 0.55 * rng.normal(),
                                      1.0, 7.0))
            lat = float(np.clip(np.log(rng.lognormal(2.6, 0.5)) - 2.6
                                + 0.3 * effort / 7.0, -2.0, 3.0))

            items = ITEM_LOAD[:, k] * 5.5 + 1.0 + 1.15 * rng.normal(size=4)
            items = np.clip(items, 1.0, 7.0)

            X[i, t] = [na, pa, arousal, stress, ctrl, soc, home,
                       np.sin(2 * np.pi * slot / N_PROMPT),
                       np.cos(2 * np.pi * slot / N_PROMPT),
                       day / (N_DAYS - 1.0), effort, perceived, lat,
                       items[0], items[1], items[2], items[3]]
            mask[i, t] = answered
            used[i, t] = k
            fitv[i, t] = f[k]
            succ[i, t] = s

    # ---- person-level targets ----------------------------------------
    # Adaptive habitual use of a family combines how often the person
    # deploys it with how well its deployment is aligned to the contexts
    # in which it works. Both components are latent: they are computed
    # from the generative state, not from the observed features.
    adapt = np.zeros((n, K_FAM))
    for i in range(n):
        for k in range(K_FAM):
            sel = used[i] == k
            if sel.sum() < 3:
                adapt[i, k] = -1.5
                continue
            freq = sel.mean()
            align = float(np.mean(fitv[i, sel]))
            gain = float(np.mean(succ[i, sel]))
            adapt[i, k] = (1.6 * align + 1.3 * gain
                           + 0.7 * np.log(freq + 0.02))
    thr = np.quantile(adapt, 0.5, axis=0)
    Y = (adapt > thr).astype(float)

    # ---- trait questionnaire proxies (validation only) ----------------
    z = lambda v: (v - v.mean()) / v.std()
    erq_reap = 4.9 + 0.9 * (0.78 * z(trait[:, 3]) +
                            0.63 * rng.normal(size=n))
    erq_supp = 3.4 + 1.1 * (0.80 * z(trait[:, 4]) +
                            0.60 * rng.normal(size=n))
    ders = 80.0 + 20.0 * (-0.66 * z(adapt.mean(axis=1))
                          - 0.30 * z(flex) + 0.69 * rng.normal(size=n))
    quest = dict(ERQ_reappraisal=np.clip(erq_reap, 1, 7),
                 ERQ_suppression=np.clip(erq_supp, 1, 7),
                 DERS_total=np.clip(ders, 36, 180))

    # ---- standardise the momentary features on observed prompts -------
    obs = mask.reshape(-1)
    flat = X.reshape(-1, F_DIM)
    m = flat[obs].mean(axis=0)
    s = flat[obs].std(axis=0) + 1e-9
    Xz = (X - m) / s
    Xz = Xz * mask[:, :, None]

    return dict(X=Xz, X_raw=X, mask=mask, Y=Y, used=used, fit=fitv,
                success=succ, adapt=adapt, trait=trait, flex=flex,
                inertia=inertia, quest=quest,
                feature_names=FEATURES, families=FAMILIES,
                fam_short=FAM_SHORT)


def splits(n=N_PART, seed=SEED):
    """Participant-level 70/15/15 training, validation and test split."""
    rng = np.random.default_rng(seed + 1)
    idx = rng.permutation(n)
    a, b = int(0.70 * n), int(0.85 * n)
    return idx[:a], idx[a:b], idx[b:]


if __name__ == "__main__":
    d = generate()
    X, mask, Y, used = d["X"], d["mask"], d["Y"], d["used"]
    print("participants %d, scheduled prompts %d, features %d"
          % X.shape)
    print("observed prompts per participant: mean %.1f (min %d, max %d)"
          % (mask.sum(1).mean(), mask.sum(1).min(), mask.sum(1).max()))
    print("compliance %.3f" % mask.mean())
    print("label prevalence:", np.round(Y.mean(0), 3))
    lab = np.corrcoef(Y.T)
    print("label correlations (off-diagonal range): %.2f to %.2f"
          % (lab[np.triu_indices(5, 1)].min(),
             lab[np.triu_indices(5, 1)].max()))
    na = d["X_raw"][:, :, 0]
    ac = []
    for i in range(X.shape[0]):
        v = na[i][mask[i]]
        if len(v) > 10:
            ac.append(np.corrcoef(v[:-1], v[1:])[0, 1])
    print("affective inertia: mean %.3f (SD %.3f)"
          % (np.mean(ac), np.std(ac)))
    q = d["quest"]
    print("ERQ reappraisal %.2f (%.2f); suppression %.2f (%.2f); "
          "DERS %.1f (%.1f)"
          % (q["ERQ_reappraisal"].mean(), q["ERQ_reappraisal"].std(),
             q["ERQ_suppression"].mean(), q["ERQ_suppression"].std(),
             q["DERS_total"].mean(), q["DERS_total"].std()))
    print("family deployment shares:",
          np.round([(used == k)[mask].mean() for k in range(K_FAM)], 3))
