"""Verbatim reviewer comments and the point-by-point responses.

Each entry is (comment, [response paragraphs]).  Placeholders {..} are filled
from the experiment tables at build time by build_responses.py.
"""

COLOUR_NOTE = {
    'R1': 'All changes made in response to your comments are marked in RED in '
          'the revised manuscript. Changes prompted by Reviewer 2 are in blue '
          'and those prompted by Reviewer 3 are in green, so that the three '
          'sets of revisions can be told apart at a glance.',
    'R2': 'All changes made in response to your comments are marked in BLUE in '
          'the revised manuscript. Changes prompted by Reviewer 1 are in red '
          'and those prompted by Reviewer 3 are in green, so that the three '
          'sets of revisions can be told apart at a glance.',
    'R3': 'All changes made in response to your comments are marked in GREEN in '
          'the revised manuscript. Changes prompted by Reviewer 1 are in red '
          'and those prompted by Reviewer 2 are in blue, so that the three '
          'sets of revisions can be told apart at a glance.',
}

OPENING = (
    'We thank you very much for the time and care you have given this '
    'manuscript. The comments were detailed and constructive, and acting on '
    'them has changed the paper substantially: the contribution is now framed '
    'as an integration framework rather than as three new operators, the lens '
    'operator is derived rather than asserted, the design objectives are stated '
    'in full, the statistical discussion is more balanced, and several new '
    'experiments have been added. Our point-by-point responses follow. {colour}')

# =====================================================================
REVIEWER1 = [
    ("""The paper claims three "improvement strategies". These techniques are not novel in the metaheuristic literature: Good point set initialization has been widely used in many swarm intelligence algorithms, Lens opposition-based learning has been applied to numerous algorithms (e.g., sand cat swarm optimization, whale optimization algorithm), Adaptive Cauchy-Gaussian mutation is a common technique for enhancing exploration-exploitation balance. The authors should: Provide a more detailed comparison table showing how their specific implementations differ from existing applications of these strategies, Emphasize the synergistic combination and the specific parameter adaptations (e.g., the dynamic k-factor in LOBL, the adaptive weights in ACGM) as the novel contribution, rather than the individual strategies themselves, Consider framing the contribution as "a novel integration framework" rather than "three new strategies".""",
     ["""Thank you for pointing this out. We agree with this comment, and we accept the premise without reservation: none of the three operator families is novel, and the submitted version did not say so clearly enough. We have therefore reframed the contribution throughout and added the comparison table you ask for.""",
      """Specifically, we have made three changes. (i) The Abstract (page 1, paragraph 2, lines 12-20) and contribution (1) in the Introduction (page 3, paragraph 3) now state explicitly that the contribution is "a novel integration framework" and that no claim of novelty is made for the individual operators; the old wording of contribution (1) is shown struck through so the change is visible. (ii) A new Section 3.6, "Novelty of the proposed integration framework" (page 9), sets out the three design decisions that distinguish this framework - the disjoint application policy that confines refraction to the inferior subpopulation and mutation to the elite, the derivation of the lens factor as a schedule with two exposed and tuned exponents, and the placement of the operators at the points of the SBOA iteration where the base algorithm is weakest. (iii) New Table 2 in that section states, operator by operator, what a typical existing application does, what MSSBOA does instead, and what the difference buys.""",
      """"The three operator families used above are established techniques, and their individual novelty is not claimed here. ... The contribution of this paper is therefore the integration framework: how each operator is re-specified for SBOA, how its control parameter is adapted, and how the three are assigned to disjoint parts of the population so that they reinforce rather than duplicate one another." (Section 3.6)""",
      """The synergy you ask us to emphasise is now also measured rather than asserted: Section 4.3 reports a full 2^3 factorial ablation from which the main effect of each strategy and the interaction between them can be read off directly (see also our reply to Reviewer 3, comments 1 and 2)."""]),

    ("""The lens opposition-based learning explanation (Section 3.2) is mathematically incomplete. Equation (11) introduces a scaling factor k, but the relationship to the "convex-lens imaging" principle is not rigorously derived. The schematic in Figure 2 is mentioned but not shown in the provided text. Provide a clearer derivation connecting the lens imaging principle to Equation (11), Show Figure 2 and explain how the "tunable scaling factor" relates to physical lens parameters, Justify why the dynamic k-factor in Equation (12) specifically uses the square root and power of 10—is this empirically determined or theoretically motivated?""",
     ["""Agree. We have, accordingly, rewritten Section 3.2 so that Equation (11) is derived rather than asserted, redrawn Figure 2, and separated the structural from the empirical justification of Equation (12). We apologise that Figure 2 did not render in the file you received; it was supplied as an EMF object and has been replaced by a new raster figure.""",
      """The derivation is now given in full (Section 3.2, page 7, paragraphs 2-4). One coordinate axis is restricted to [lb_j, ub_j] and its midpoint o_j = (lb_j + ub_j)/2 is taken as the optical centre of a thin convex lens. The current individual is an object of height h standing at x_j; the lens forms an inverted real image of height h* at x*_j. Because the ray through the optical centre is undeviated, the object and image triangles share vertically opposite angles at o_j and are similar, which gives h/h* = (x_j - o_j)/(o_j - x*_j). Defining k = h/h* and solving for x*_j yields exactly Equation (11); k = 1 recovers classical opposition-based learning.""",
      """On the relation to physical lens parameters: k is the ratio of object height to image height, that is, the reciprocal of the transverse magnification of the virtual lens. It is the single lens parameter the operator exposes, and it is not a free numerical constant. New Figure 2a shows the similar-triangle construction with h, h*, x_j - o_j and o_j - x*_j labelled, Figure 2b plots k(t) for several exponent pairs, and Figure 2c plots the induced contraction ratio 1/k.""",
      """Your question about the square root and the power of 10 also uncovered an error of interpretation in the submitted version, which we have corrected. Equation (11) implies |x*_j - o_j| = |x_j - o_j|/k, so k controls the radius of the refracted point about the interval midpoint, not its distance from the parent. The submitted text stated that a large k "keeps the refracted solution close to the current one", which is wrong; the corrected text states that a large k contracts the image onto the neighbourhood of o_j. We are grateful for the question, because the erroneous reading had gone unnoticed.""",
      """As to whether the exponents are theoretical or empirical, they are partly both, and Section 3.2 now says which is which. Three requirements are structural: k(0) = 1 so the operator starts as exact opposition-based learning; k must be monotone so the contraction does not oscillate; and k must span orders of magnitude, which the power mu supplies since k(T) = 2^mu. Within those constraints the two exponents are free and were chosen empirically. New Table 1 reports a grid over the root nu and the power mu on the CEC2017 suite, including the constant k = 1. {k_finding}"""]),

    ("""Below paper can help to improve the quality of the manuscript: [Hesam et al., 2024, Expert Systems] (https://onlinelibrary.wiley.com/doi/10.1111/exsy.13306)""",
     ["""Thank you for the pointer. The paper is Safari, A. and Varaee, H., "Opposition-based ideal gas molecular movement algorithm with Cauchy mutation, velocity clamping, and mirror operator", Expert Systems 2023, 40, e13306. It is directly relevant, because it combines opposition-based learning with Cauchy mutation in one algorithm, which is the closest published precedent for the combination we use, and it therefore strengthens rather than weakens the case that our contribution lies in the integration and not in the operators.""",
      """We have added it as reference [81] and cited it in the new Section 3.6, where it is used as evidence that combinations of this kind are already established: "a closely related combination of opposition-based learning with Cauchy mutation, velocity clamping and a mirror operator has recently been reported for the ideal gas molecular movement algorithm [81]"."""]),

    ("""The color-harmony optimization formulation is incomplete in the provided manuscript. The authors mention Equation (18) and (19) for color-harmony evaluation, but these equations are not fully presented in the text (the manuscript appears to be missing pages where these formulas should appear). Ensure all equations are complete and properly numbered, Provide clear definitions of all variables in the color model, Explain the color space used (RGB, HSV, Lab, etc.) and justify the choice, Describe how the harmonic template is determined (Figure 12a references a template but it's not clear how it's derived)""",
     ["""Agree, and thank you for catching this. We have completed Section 5.1 on all four points.""",
      """Equations (18) and (19) are now written out in full in the running text as well as in the display equations (Section 5.1, page 15). DIV is the mean normalized pairwise arc distance of the K hues, equal to 0 for a monochrome palette and 1 when every pair of hues is complementary; CON = min(1, (max_i v_i - min_i v_i)/0.6) saturates once the palette spans 60% of the value range. The objective is f(P) = w_har HAR(P) + w_div DIV(P) + w_con CON(P) with w_har = 0.60, w_div = 0.25, w_con = 0.15. All three terms lie in [0, 1], so the reported harmony score is 100 f(P) per cent, which also makes the scale of Table 14 explicit.""",
      """On the colour space: the model works in HSV, and a new paragraph explains why this is forced by the objective rather than chosen for convenience. Matsuda's templates are angular sectors on the hue wheel, so hue must be an explicit cyclic coordinate; RGB has no such coordinate, and CIE L*a*b* carries hue only implicitly as the argument of (a*, b*), which would prevent the arc distance of Equation (15) from being written in closed form. HSV also supplies saturation, which weights how much hue information a colour carries, and value, which supplies the tonal contrast. The decision variables are the triples (h_i, s_i, v_i) with h_i in [0, 360), s_i in [0.2, 1] and v_i in [0.15, 1]; the lower bounds exclude the near-grey and near-black region where hue is perceptually meaningless.""",
      """On the harmonic template: the template is an output of the evaluation, not an input. New Table 13 lists the seven chromatic templates of Matsuda in the parameterization of Cohen-Or et al., each as one or two sectors of fixed angular width and fixed relative offset. The only free parameter is a rigid rotation alpha. For each candidate palette the disharmony energy of Equation (16) is minimized over the seven templates and over alpha on a 5-degree grid, and the best-fitting pair is what Figure 12a displays. We have stated this explicitly so the figure can no longer be read as showing a designer-chosen template."""]),

    ("""The Wilcoxon rank-sum test results in Table 7 show MSSBOA winning "83/18/15" against QIO and LSHADE, but the paper concludes "only a few losses on high-dimensional problems." However, 15 losses out of 116 cases (12.9%) is not negligible. Please provide a more balanced discussion of the statistical results, Analyze whether the losses occur on specific function types (unimodal, multimodal, hybrid, composition) to identify potential weaknesses, Consider whether the performance gap narrows with increasing dimensionality (as acknowledged in the limitations section)""",
     ["""Agree. The sentence you quote was indefensible and we have removed it. Section 4.4 now gives a balanced reading, a breakdown by function class and an explicit dimensional analysis.""",
      """On balance: the revised text states that MSSBOA is significantly better than QIO on 71.6% of cases and than LSHADE on 70.7%, that it loses 12.9% of cases to each, and that a further 18 and 19 cases are statistically indistinguishable - so on roughly three cases in ten these two algorithms are at least as good as the proposed method. The text says in as many words that "this is a real limitation and not a rounding error".""",
      """On function class: new Table 11 breaks the losses down using the per-function ranks already published in Tables A5-A8, so the analysis is consistent with the data you have. The losses are not uniform. Against QIO they concentrate on the composition functions F21-F30, which account for 8 of the 16 rank losses although composition functions supply only 40 of the 116 cases, and none occurs on a unimodal function. Against LSHADE the profile is reversed: 10 of the 20 rank losses fall on F1-F10. We interpret this as a specific rather than a general weakness - the elite-guided intensification of MSSBOA is less effective when a landscape has many equally deep basins whose relative depth only becomes apparent late in the run, which is exactly the structure of the CEC2017 composition functions.""",
      """On dimensionality: your suspicion is confirmed by the data. The mean rank gap to QIO falls monotonically from 2.103 at 30D to 1.103 at 100D, and the gap to RIME from 2.379 to 1.517, while losses against QIO, RIME and LSHADE rise from 0, 0 and 3 at 30D to 7, 6 and 6 at 100D. The revised text concludes that the results establish MSSBOA as competitive with the best available algorithms at high dimension rather than dominant over them, and the limitations section now identifies the mechanism (both added operators are elite-centred and consume a dimension-independent share of the budget)."""]),

    ("""The parameter sensitivity analysis only examines two parameters (N_min and p_m) using Friedman rankings. The paper does not investigate: Population size N (fixed at 30), The threshold for applying LOBL (fixed at 30%), The β parameter in the Lévy flight (fixed at 1.5), The three-stage time division (T/3, 2T/3) in the hunting strategy. Justify why these parameters are fixed at their current values, Consider adding ablation studies for these parameters or citing prior work that establishes their optimal values, If these parameters are problem-dependent, discuss how they might be tuned for different applications.""",
     ["""Agree, and this comment also exposed an inconsistency in the submitted manuscript that we are glad to correct. Section 3.2 described LOBL as being applied to "the worst 30%" of the population, whereas Table 3 and the sensitivity study in Table 4 both use N_min = 0.2N. The 30% was a leftover from an earlier draft; the value actually used, and the value the grid search selects, is 0.2N. Section 3.2 and Algorithm 1 have been corrected, so the LOBL threshold is not in fact a fixed, unexamined parameter - it is the parameter swept in Table 4, and we have renamed it explicitly to avoid the ambiguity.""",
      """For the remaining three parameters we have added a new sensitivity study rather than only argue from prior work. Section 4.2 now reports grids over the population size N, the Levy stability index beta and the three-stage time division, on the CEC2017 suite in 10 dimensions with 20 independent runs per setting, analysed by the same Friedman protocol as the existing Tables 4 and 5. {param_finding}""",
      """We have also stated the prior grounds where they exist, since these are not free choices. beta = 1.5 is the value used in the original SBOA [51] and, before it, the standard value for Levy flights in the Mantegna formulation [57,58], and changing it would make the comparison with SBOA confounded. N = 30 is the population size used by every comparison algorithm in Table 3, so it is fixed for fairness rather than for performance. The three-stage division T/3, 2T/3 is inherited unchanged from SBOA [51] and is part of the base algorithm rather than of our contribution; we kept it so that the ablation in Section 4.3 measures our operators and not a re-tuning of SBOA.""",
      """On problem dependence: the revised limitations section notes that the framework adds three parameters to those of SBOA and that this increases the tuning burden, and it recommends a self-adaptive scheme in which p_m and the LOBL ratio respond to a measured diversity statistic as the natural next step."""]),

    ("""In Equation (22), the weights for the aesthetic objective are: BM=0.30, OV=0.22, AL=0.18, SY=0.15, DEN=0.15. The paper cites Ngo et al. [73] for these weights, but does not discuss: Whether these weights are universally applicable or problem-specific, Whether they were empirically validated for the specific design problems in Table 9, The sensitivity of results to variations in these weights. Add a brief discussion of the weight selection and consider showing results with alternative weight configurations.""",
     ["""Agree. Section 5.2 now discusses the weights explicitly and reports results under alternative configurations.""",
      """On the first two points we answer plainly: the weights are not universal, and they were not independently validated on the eight problems of Table 15. They follow the relative importance Ngo et al. [73] assign to their measures, which was derived from a corpus of screen interfaces; there is no reason to expect the same ordering for, say, a packaging label, where overlap is a hard production constraint rather than an aesthetic preference. The revised text says so: "They are not universal constants ... adopting them unchanged is a modelling choice, and it should be read as one."."""
      ,
      """On sensitivity, we have re-optimized all eight problems under five weight configurations - the Ngo-based setting W0, equal weights, and three configurations that each promote one term - and report the outcome in new Table 17, together with Kendall's tau between the algorithm ordering under each configuration and under W0. {weights_finding}"""]),

    ("""The limitations section (Conclusions) mentions three limitations, but two of them ("parameters are determined empirically" and "high-dimensional search ability should be strengthened") are acknowledged in the original SBOA paper as well. Discuss which specific limitations of MSSBOA are unique to this variant versus inherited from SBOA, Provide more concrete suggestions for addressing each limitation, Consider including preliminary results or analysis that demonstrate these limitations.""",
     ["""Agree. The limitations section has been rewritten and now separates inherited from variant-specific limitations, attaches a concrete remedy to each, and points to the analysis that demonstrates it.""",
      """Inherited: empirical parameter determination is a property of SBOA and of the family generally. What is specific to MSSBOA is that the framework adds three further parameters - the LOBL ratio, p_m and the two exponents of the lens schedule - so the burden grows rather than changes in kind; the concrete remedy proposed is a self-adaptive scheme driven by a measured diversity statistic. Partly inherited: the weakening at high dimension, but Section 4.4 now shows a MSSBOA-specific component and identifies the mechanism - both added operators are elite-centred and consume a dimension-independent share of the budget, so as D grows the same number of refractions and mutations must cover an exponentially larger space; the remedy proposed is a dimension-aware budget in which the LOBL subpopulation or mutation frequency scales with D.""",
      """Genuinely specific to this variant: the lens operator refracts about the midpoint of the static search interval, so as k grows the image contracts onto a fixed point that carries no information about where the population currently is. The remedy is to replace the static bounds by the per-dimension extrema of the current population so that the optical centre tracks the population centroid; we note that this is a change to Equation (11) itself and not merely to its parameters, and we leave it to future work rather than claim it here. This limitation is demonstrated by the loss analysis of Table 11 and by the k-schedule grid of Table 1."""]),

    ("""The manuscript contains several typographical and formatting issues: Inconsistent use of mathematical notation (e.g., "CauchyGaussian" vs. "Cauchy-Gaussian"); Incomplete table entries with "td rowspan" tags visible; Duplicate page numbering in the appendix tables; Reference formatting inconsistencies""",
     ["""Thank you. We have gone through the manuscript for all four items.""",
      """The notation is now uniform: every occurrence of the compound is set as "Cauchy-Gaussian" with an en dash, including the previously truncated "Cauchy-Gauss mutation" in Algorithm 1. On the "td rowspan" tags and the duplicate page numbering: we inspected the source file and could not reproduce either artefact in it, and we believe both arose in the PDF that was generated from our submission rather than in the document itself. We have nevertheless rebuilt the appendix tables so that their header rows are marked to repeat across page breaks, which is the most likely origin of an apparent duplication, and we would be grateful if the editorial office would check the typeset proof for these two items. The references have been reformatted consistently in MDPI style, and the three new references [81-83] follow the same format."""]),

    ("""Will the source code for MSSBOA be made publicly available to facilitate reproduction and comparison?""",
     ["""Yes. The complete source code is released with the paper: the MSSBOA implementation, the re-implementations of the comparison algorithms used in the new Section 4.5, the two design-problem formulations, the experiment runners and all raw result files. The Data Availability Statement has been updated accordingly and now gives the repository address instead of "available on request"."""]),

    ("""The design problems considered are offline optimization tasks. Could MSSBOA be adapted for interactive or real-time design scenarios where users provide subjective feedback?""",
     ["""Yes, and we think the framework is unusually well suited to it, but we have been careful to present this as a direction rather than a result. A new paragraph in the Conclusions explains what adaptation would involve: the analytic objective would be replaced by a surrogate model fitted to accumulated user judgements so that only a small number of candidates is ever shown to the user, with the population and iteration budget reduced accordingly. The reason the framework fits is structural - a human evaluation budget is tiny, and MSSBOA is explicitly designed to spend very few evaluations on the elite, which is where interactive evaluation is most valuable. We cite the interactive genetic protocols for colour matching in cultural-creative design [79,80] as the natural starting point."""]),

    ("""The aesthetic evaluations use computational models. Have the generated designs been validated with human subjects to confirm the aesthetic superiority?""",
     ["""No, they have not, and we have added this as an explicit limitation rather than leave it implicit. The revised Conclusions state that, strictly, the claim established here is that MSSBOA optimizes these models better, not that it produces better designs. We note that the models are themselves grounded in human data - the harmonic templates come from Matsuda's scheme as formalized by Cohen-Or et al. [70,72], and the layout measures of Ngo et al. [73,75] were calibrated against human ratings in their original studies - but we also say plainly that this grounding transfers only as far as the models do. A controlled study in which trained designers and naive participants rank the generated palettes and layouts against baselines, with agreement measured against the computational scores, is described as a necessary complement and is planned as the next stage of this work."""]),

    ("""The maximum problem dimension in the layout problems appears to be 12 (DL04, 6 elements × 2 coordinates). Could the algorithm handle more complex layouts with 20-30 elements?""",
     ["""Agree that 12 dimensions is too small to support a claim of practical applicability, and we have run the experiment rather than argue the point. A new Section 5.3, "Scalability of the layout problem", instantiates the same objective with 8, 12, 20 and 30 elements, giving problems of 16 to 60 dimensions, with the total element area held at about half the canvas so that the density term stays comparable across sizes. New Table 18 reports the mean aesthetic score of MSSBOA and five comparison algorithms at each size. {scale_finding}"""]),
]

# =====================================================================
REVIEWER2 = [
    ("""Why do authors choose SBOA as the basis of this research? There are numerous MAs in recent decades, and the motivation for choosing SBOA is unclear.""",
     ["""Thank you for pointing this out. We agree that the submitted version asserted the choice rather than justified it. We have therefore added a paragraph to the Introduction (page 3, paragraph 2) giving three concrete reasons.""",
      """The first and most important is structural fit. Aesthetic objectives such as Equations (19) and (22) are sums of competing terms whose trade-off surface has many broad, shallow optima rather than one sharp optimum, so an optimizer must survey widely before committing. SBOA is one of the few recent metaheuristics whose exploration phase is split into three explicitly time-gated stages with qualitatively different step distributions - a differential perturbation, a Brownian move towards the elite and a Levy flight - which gives a scheduled and inspectable progression from survey to commitment and, equally important for this study, well-defined points at which further operators can be inserted.""",
      """The second is economy: SBOA has a single control parameter beyond the population size, so a study of added operators is not confounded by re-tuning of the base algorithm. The third is that SBOA is recent enough for its weaknesses to be documented but not yet addressed for this problem class, while having been shown competitive on standard suites [51], which makes it a meaningful baseline rather than a straw man."""]),

    ("""The novelty of the new algorithm is limited. The authors combine well-known operators into SBOA to form MSSBOA, but the application is interesting.""",
     ["""We agree, and we have stopped claiming otherwise. Reviewer 1 raised the same point, and the manuscript has been reframed accordingly: the Abstract and contribution (1) now state that the contribution is an integration framework and that no novelty is claimed for the individual operators, and a new Section 3.6 sets out precisely what differs from existing applications of the same operators, with new Table 2 stating it operator by operator.""",
      """We have also tried to make the claim testable rather than rhetorical. Section 4.3 now reports a full 2^3 factorial ablation, so that the main effect of each operator and the interaction between them can be read off the data; if the operators were merely stacked, the interaction would be negligible, and reporting it either way seemed to us the honest way to support or refute a claim of synergy.""",
      """We are glad the application is of interest, and we have strengthened that side of the paper as well: the colour model is now specified completely (Section 5.1), the layout weights are examined for sensitivity (Section 5.2), and a new Section 5.3 extends the layout problem to 30 elements."""]),

    ("""The authors present a literature review of SBOA's variants, but do not compare their performance. I encourage authors to use some SBOA's variants for experimental comparison.""",
     ["""Agree, and this was a fair criticism: reviewing variants without comparing against them is not much of a comparison. We have added a new Section 4.5, "Comparison with recent SBOA variants and multi-strategy algorithms", in which MSSBOA is compared directly with three of the variants reviewed in the Introduction - MISBOA [53] with its incremental-PID feedback regulation and co-operative camouflage, CGSBOA [54] with its multi-strategy fusion and Cauchy-Gaussian crossover, and LTSBOA [55] with its logistic-tent chaotic initialization and crossover strategy. Following Reviewer 3 we have also included two recent multi-strategy algorithms from outside the SBOA family, MS-TSA and I-CPA, together with their base algorithms TSA and CPA so that the gain of each variant over its own base is visible rather than assumed.""",
      """We should be transparent about one methodological point. The source codes of these variants are not publicly distributed, so each was re-implemented from the equations, control parameters and pseudo-code given in the corresponding paper. To make that auditable, our implementations are released with the paper, and every algorithm is charged for every function evaluation it performs, including those consumed by auxiliary operators. New Table 12 reports the Friedman ranking and the pairwise Wilcoxon outcome. {variants_finding}"""]),
]

# =====================================================================
REVIEWER3 = [
    ("""It is stated that the best performance was achieved through the simultaneous use of the three proposed methods. However, the individual contribution of each method to the algorithm must also be clearly demonstrated. How does the algorithm's performance change when these methods are applied separately? Have the three different results obtained by using each strategy on its own been compared? Presenting an ablation analysis in this context would facilitate a clearer understanding of the contribution of the proposed methods.""",
     ["""Thank you for this comment. An ablation of exactly this kind was in fact present in the submitted version - Section 4.3, Tables 6 and 7 and Figure 6 report SBOA-GPSI, SBOA-LOBL and SBOA-ACGM, each adding one strategy to the basic SBOA, over four dimensions with the full statistics in Appendix Tables A1-A4. We take from your comment that this was not signposted clearly enough, and we have made it more prominent, but we have also gone further, because your comment 2 asks a question that single-strategy ablation cannot answer.""",
      """Section 4.3 has therefore been extended from three single-strategy variants to the complete 2^3 factorial design: all eight combinations of the three strategies, from the basic SBOA to the full MSSBOA, run under identical conditions. This subsumes the original ablation - the single-strategy rows are still there - while adding the four combinations that were missing. New Table 8 reports every configuration with its Friedman ranking and its Wilcoxon outcome against the basic SBOA. {factorial_finding}"""]),

    ("""It should be clarified whether the decision to use the three methods together is based on the results obtained from the individual experiments in question. In other words, the rationale for using the methods in combination and the complementary interaction between them should be set out in greater detail.""",
     ["""Agree, and this is the more penetrating of the two questions, because a set of individually beneficial operators need not be beneficial together. The factorial design described above was added precisely so that this can be answered with a number rather than an assertion.""",
      """From the factorial results we now report the average main effect of each strategy on the mean Friedman rank, computed over the other two factors, and the three-way interaction. {factorial_finding}""",
      """We have also set out the design rationale rather than leaving it implicit. New Section 3.6 explains why the three operators are expected to be complementary: they act on disjoint parts of the population and at different points of the iteration. LOBL is applied only to the inferior individuals, so it restores diversity where it has been lost without being able to displace the elite; ACGM is applied only to the elite, which is the single individual that both SBOA phases read from and that neither can perturb; and GPSI acts once, before either operator runs. Because their domains do not overlap, the operators cannot undo one another's work, which is the mechanism by which a combination can be more than the sum of its parts."""]),

    ("""The use of the CEC2017 test functions is of great importance in terms of evaluating the fundamental optimisation performance of the developed algorithm. However, in order to demonstrate more clearly the position of the proposed method within the current literature, it is recommended that the results be compared with those of the MS-TSA and I-CPA algorithms proposed in recent years.""",
     ["""Agree, and thank you for naming specific comparators. Both have been added to the new Section 4.5. MS-TSA is Beskirli, Dag and Kiran, "A tree seed algorithm with multi-strategy for parameter estimation of solar photovoltaic models", Applied Soft Computing 2024, 167, 112220, which combines a self-adaptive weighting mechanism, chaotic elite learning and experience-based learning; I-CPA is Beskirli and Dag, "I-CPA: an improved carnivorous plant algorithm for solar photovoltaic parameter identification problem", Biomimetics 2023, 8, 569, which strengthens the exploitation phase of the carnivorous plant algorithm with a teaching-factor strategy. They are cited as references [82] and [83].""",
      """We have included their base algorithms, TSA and CPA, alongside them, so that the improvement each variant achieves over its own base is visible in the same table rather than taken on trust; this seemed to us the fairest way to position MSSBOA against methods built on very different foundations. As noted in our reply to Reviewer 2, the source codes are not publicly distributed, so both were re-implemented from the published equations and parameter settings, and our implementations are released with the paper. New Table 12 reports the outcome. {variants_finding}"""]),

    ("""In Figures 4 and 5, the word 'best' located below the optimal solution point does not appear sufficiently legible. To improve the clarity of the figure, it is recommended that this text be moved above the relevant point and that the font size be made more prominent.""",
     ["""Agree, and thank you for the specific and easily actionable suggestion. Figures 4 and 5 have been redrawn. The annotation marking the best setting is now placed above the corresponding point rather than below it, its font size has been increased substantially and set in bold, and it is enclosed in a boxed callout with a leader line to the marker so that the association with the point is unambiguous. The marked point is additionally ringed. The annotation now also reports the mean rank value of the best setting, which the earlier version did not. The captions of both figures have been updated to say that the best setting is marked above the corresponding point."""]),

    ("""Sharing the source code relating to the improvements made in this study via GitHub or a similar open-access platform would significantly contribute to the method's reproducibility and reliability. Should the article be accepted, making the code publicly available would enhance the study's scientific value, visibility and usability in future research.""",
     ["""We agree entirely, and we have not made it conditional on acceptance. The complete source code is released now: the MSSBOA implementation, the re-implementations of MISBOA, CGSBOA, LTSBOA, MS-TSA, I-CPA and their base algorithms, the two design-problem formulations, the experiment runners, the statistical analysis scripts and all raw result files. The Data Availability Statement has been rewritten to give the repository address in place of the previous "available on request from the corresponding author"."""]),
]
